//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_com_hedge
    {
        public acc_com_hedge()
        {
            this.contas_a_pagar_plano_de_contas = new HashSet<contas_a_pagar_plano_de_contas>();
            this.referencia_hedge = new HashSet<referencia_hedge>();
            this.fluxo_de_caixa = new HashSet<fluxo_de_caixa>();
            this.movimento_bancario = new HashSet<movimento_bancario>();
            this.movimento_bancario1 = new HashSet<movimento_bancario>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_ACC { get; set; }
        public int INT_ID_INSTITUICAO { get; set; }
        public System.DateTime DATE_DATA { get; set; }
        public decimal FLOAT_VALOR { get; set; }
        public decimal FLOAT_SALDO_COM_HEDGE { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public int INT_ID_FUNC { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public decimal FLOAT_NIVEL_HEDIADO { get; set; }
        public System.DateTime DATE_VENCIMENTO { get; set; }
        public Nullable<System.DateTime> DATE_LIQUIDACAO { get; set; }
        public decimal DECIMAL_TAXA_PTAX_DA_LIQ { get; set; }
        public decimal DECIMAL_JUROS_EM_DOLAR { get; set; }
        public bool BOOL_ACC_EMPRESTIMO { get; set; }
        public Nullable<int> INT_ID_CATEGORIA_EMPRESTIMO { get; set; }
        public bool BOOL_CAMBIO_PRONTO { get; set; }
        public int INT_ID_EMPRESA { get; set; }
        public decimal DECIMAL_IOF { get; set; }
        public decimal DECIMAL_TAXA_DE_JUROS { get; set; }
        public string CHAR_TIPO_DE_JUROS { get; set; }
        public int INT_TEMPO_CARENCIA { get; set; }
        public bool BOOL_GARANTIA { get; set; }
        public string TXT_GARANTIA { get; set; }
        public decimal DECIMAL_SEGURO { get; set; }
        public decimal DECIMAL_TAXA_ADM { get; set; }
        public string TXT_BEM { get; set; }
        public bool BOOL_REAL_DOLAR { get; set; }
        public string TXT_OBS { get; set; }
        public int INT_NR_PARCELAS { get; set; }
        public Nullable<int> INT_D { get; set; }
        public string TXT_NUMERO_ORDEM_DE_PAGAMENTO { get; set; }
        public Nullable<int> INT_ID_CONTA_BANCARIA_EMPRESA { get; set; }
        public bool BOOL_COM_HEDGE { get; set; }
        public bool BOOL_JUROS_AM_AA { get; set; }
    
        public virtual categoria_de_emprestimo_com_banco categoria_de_emprestimo_com_banco { get; set; }
        public virtual contas_bancarias_empresa contas_bancarias_empresa { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual ICollection<contas_a_pagar_plano_de_contas> contas_a_pagar_plano_de_contas { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual instituicao instituicao { get; set; }
        public virtual ICollection<referencia_hedge> referencia_hedge { get; set; }
        public virtual ICollection<fluxo_de_caixa> fluxo_de_caixa { get; set; }
        public virtual ICollection<movimento_bancario> movimento_bancario { get; set; }
        public virtual ICollection<movimento_bancario> movimento_bancario1 { get; set; }
    }
}
