//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class agendamento_certificacao
    {
        public agendamento_certificacao()
        {
            this.agendamento_certificacao_itens_especificos = new HashSet<agendamento_certificacao_itens_especificos>();
            this.agendamento_esquema = new HashSet<agendamento_esquema>();
            this.agendamento_formulario_ser_aplicado = new HashSet<agendamento_formulario_ser_aplicado>();
            this.agendamento_talhao_propriedade = new HashSet<agendamento_talhao_propriedade>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_COLABORADOR_QUE_VAI_APLICAR { get; set; }
        public int INT_ID_TIPO_INSPECAO { get; set; }
        public System.DateTime DATE_AGENDAMENTO { get; set; }
        public Nullable<int> INT_ID_COOPERADO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public System.TimeSpan TEMPO_ESTIMADO { get; set; }
        public int INT_ID_CADASTRO { get; set; }
        public System.DateTime DATE_CADASTRO { get; set; }
        public Nullable<int> INT_ID_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DATE_ALTERACAO { get; set; }
        public Nullable<int> INT_ID_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DATE_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DATE_INICIO { get; set; }
        public Nullable<System.DateTime> DATE_FINALIZACAO { get; set; }
        public bool BOOL_SINCRONIZACAO_INICIO { get; set; }
        public Nullable<System.DateTime> DATE_SINCRONIZACAO { get; set; }
        public bool BOOL_SINCRONIZACAO_FINALIZOU { get; set; }
        public Nullable<System.DateTime> DATE_SINC_FIN { get; set; }
        public Nullable<int> INT_ID_SOLICITACAO_VISITA { get; set; }
        public bool BOOL_FAZER_EXERCICIO_RASTREABILIDADE { get; set; }
        public bool BOOL_ITENS_ESPECIFICOS_FORMULARIO_COMPLETO { get; set; }
        public Nullable<int> INT_ID_SETOR { get; set; }
        public Nullable<int> INT_ID_RESPONSAVEL_SETOR { get; set; }
        public bool BOOL_VISITA_CANCELADA { get; set; }
        public string TXT_MOTIVO { get; set; }
        public bool BOOL_REMARCADA { get; set; }
        public string TXT_OBS { get; set; }
        public bool BOOL_INTERNO { get; set; }
    
        public virtual ICollection<agendamento_certificacao_itens_especificos> agendamento_certificacao_itens_especificos { get; set; }
        public virtual ICollection<agendamento_esquema> agendamento_esquema { get; set; }
        public virtual ICollection<agendamento_formulario_ser_aplicado> agendamento_formulario_ser_aplicado { get; set; }
        public virtual ICollection<agendamento_talhao_propriedade> agendamento_talhao_propriedade { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        public virtual funcionario funcionario2 { get; set; }
        public virtual cooperado cooperado { get; set; }
        public virtual funcionario funcionario3 { get; set; }
        public virtual funcionario funcionario4 { get; set; }
        public virtual setor setor { get; set; }
        public virtual solicitar_visita solicitar_visita { get; set; }
        public virtual tipo_de_inspecao tipo_de_inspecao { get; set; }
    }
}
