//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class agendamento_talhao_propriedade
    {
        public agendamento_talhao_propriedade()
        {
            this.formulario_aplicar_agendamento_talhao_propriedade = new HashSet<formulario_aplicar_agendamento_talhao_propriedade>();
        }
    
        public int INT_ID { get; set; }
        public Nullable<int> INT_ID_TALHAO { get; set; }
        public int INT_ID_PROPRIEDADE { get; set; }
        public int INT_ID_AGENDAMENTO { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual agendamento_certificacao agendamento_certificacao { get; set; }
        public virtual propriedade propriedade { get; set; }
        public virtual talhao talhao { get; set; }
        public virtual ICollection<formulario_aplicar_agendamento_talhao_propriedade> formulario_aplicar_agendamento_talhao_propriedade { get; set; }
    }
}
