//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class agendamento_certificacao_itens_especificos
    {
        public int INT_ID { get; set; }
        public int INT_ID_AGENDAMENTO { get; set; }
        public int INT_ID_FORM_SUB_ITEM { get; set; }
        public string TXT_OBS { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual agendamento_certificacao agendamento_certificacao { get; set; }
        public virtual formulario_sub_item formulario_sub_item { get; set; }
    }
}
