//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class agendamento_cooperado
    {
        public agendamento_cooperado()
        {
            this.agendamento_situacao_norma = new HashSet<agendamento_situacao_norma>();
            this.cadastro_entrada = new HashSet<cadastro_entrada>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_AGENDAMENTO { get; set; }
        public int INT_ID_COOPERADO { get; set; }
        public Nullable<int> INT_ID_TALHAO { get; set; }
        public Nullable<int> INT_ID_SUBTIPO { get; set; }
        public decimal DECIMAL_SACAS { get; set; }
        public bool BOOL_CAFE_BORDADURA { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public int INT_ID_FUNCIONARIO { get; set; }
        public System.DateTime DATA_LANCAMENTO { get; set; }
        public bool BOOL_BLOQUEAR_LOTE { get; set; }
        public string TXT_MOTIVO_BLOQUEIO { get; set; }
        public Nullable<int> INT_ID_COMPRA_FECHAMENTO_FUT_TERCEIRO { get; set; }
    
        public virtual agendamento_carga_descarga agendamento_carga_descarga { get; set; }
        public virtual cooperado_que_fazem_parte_do_mercado_futuro cooperado_que_fazem_parte_do_mercado_futuro { get; set; }
        public virtual ICollection<agendamento_situacao_norma> agendamento_situacao_norma { get; set; }
        public virtual cooperado cooperado { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual subtipo_norma subtipo_norma { get; set; }
        public virtual talhao talhao { get; set; }
        public virtual ICollection<cadastro_entrada> cadastro_entrada { get; set; }
    }
}
