//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class agendamento_esquema
    {
        public int INT_ID { get; set; }
        public int INT_ID_AGENDAMENTO { get; set; }
        public int INT_ID_NORMAS { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual agendamento_certificacao agendamento_certificacao { get; set; }
        public virtual norma norma { get; set; }
    }
}
