//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class agendamento_carga_descarga
    {
        public agendamento_carga_descarga()
        {
            this.agendamento_cooperado = new HashSet<agendamento_cooperado>();
        }
    
        public int INT_ID { get; set; }
        public Nullable<int> INT_ID_MOTORISTA { get; set; }
        public Nullable<int> INT_ID_CONTRATO { get; set; }
        public System.DateTime DATE_HORA_INICIO { get; set; }
        public System.DateTime DATE_HORA_FIM { get; set; }
        public decimal DECIMAL_SACAS { get; set; }
        public bool BOOL_CARGA_DESCARGA { get; set; }
        public string TXT_OBS { get; set; }
        public Nullable<System.DateTime> DATE_HORA_CHEGOU { get; set; }
        public Nullable<System.DateTime> DATE_HORA_PESAGEM { get; set; }
        public Nullable<System.DateTime> DATE_HORA_FINALIZOU { get; set; }
        public string CHAR_STATUS { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public int INT_ID_ALMOXARIFADO { get; set; }
        public string TXT_SAFRA { get; set; }
        public int INT_SACAS_DESCARREGA_POR_HORA { get; set; }
        public string TXT_PLACA { get; set; }
        public int INT_ID_FUNCIONARIO { get; set; }
        public System.DateTime DATA_LANCAMENTO { get; set; }
        public Nullable<int> INT_ID_FECHAMENTO_MERCADO_FUTURO { get; set; }
    
        public virtual contrato contrato { get; set; }
        public virtual almoxarifado almoxarifado { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual fechamento_mercado_futuro fechamento_mercado_futuro { get; set; }
        public virtual ICollection<agendamento_cooperado> agendamento_cooperado { get; set; }
        public virtual motorista motorista { get; set; }
    }
}
