//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class alas_do_armazem_lotes
    {
        public alas_do_armazem_lotes()
        {
            this.alas_do_armazem_lotes1 = new HashSet<alas_do_armazem_lotes>();
            this.remocao_de_lotes = new HashSet<remocao_de_lotes>();
        }
    
        public int INT_ID { get; set; }
        public Nullable<int> INT_ID_CADASTRO_ENTRADA { get; set; }
        public Nullable<int> INT_ID_LOTE_ARMAZEM_TERCEIROS { get; set; }
        public Nullable<int> INT_ID_LOTE_RESULTADO_REBENEFICIO { get; set; }
        public Nullable<int> INT_ID_ALA { get; set; }
        public int INT_ID_RESPONSAVEL { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public bool BOOL_FINALIZAR_POSICAO { get; set; }
        public Nullable<int> INT_ID_RESPONSAVEL_POR_FINALIZAR_A_POSICAO { get; set; }
        public Nullable<System.DateTime> DATE_FINALIZOU_POSICAO { get; set; }
        public decimal DECIMAL_PESO_LIQUIDO { get; set; }
        public decimal DECIMAL_TARA { get; set; }
        public int INT_SEQUENCIA { get; set; }
        public bool BOOL_CAPTURA_DE_PESO_MANUAL { get; set; }
        public string TXT_MOTIVO_EXCLUSAO { get; set; }
        public Nullable<int> INT_ID_RFID { get; set; }
        public Nullable<int> INT_ID_BALANCA { get; set; }
        public System.DateTime DATE_ULTIMA_ALTERACAO { get; set; }
        public Nullable<int> INT_ID_ALA_ORIGEM_DIVIDIU_BAG { get; set; }
    
        public virtual alas_do_armazem alas_do_armazem { get; set; }
        public virtual alas_do_armazem alas_do_armazem1 { get; set; }
        public virtual ICollection<alas_do_armazem_lotes> alas_do_armazem_lotes1 { get; set; }
        public virtual alas_do_armazem_lotes alas_do_armazem_lotes2 { get; set; }
        public virtual cadastro_entrada cadastro_entrada { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual lote_armazem_terceiros lote_armazem_terceiros { get; set; }
        public virtual lote_resultado_rebeneficio lote_resultado_rebeneficio { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        public virtual rfid_chip rfid_chip { get; set; }
        public virtual ICollection<remocao_de_lotes> remocao_de_lotes { get; set; }
    }
}
