//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class almoxarifado
    {
        public almoxarifado()
        {
            this.agendamento_carga_descarga = new HashSet<agendamento_carga_descarga>();
            this.alas_do_armazem = new HashSet<alas_do_armazem>();
            this.autorizacao_generica = new HashSet<autorizacao_generica>();
            this.carregamento_para_armazem_terceiros = new HashSet<carregamento_para_armazem_terceiros>();
            this.instrucao_preparo = new HashSet<instrucao_preparo>();
            this.resultado_rebeneficio = new HashSet<resultado_rebeneficio>();
            this.cadastro_entrada = new HashSet<cadastro_entrada>();
            this.autorizacao_generica1 = new HashSet<autorizacao_generica>();
            this.contrato = new HashSet<contrato>();
            this.contrato1 = new HashSet<contrato>();
            this.fechamento_mercado_futuro = new HashSet<fechamento_mercado_futuro>();
            this.lote_produto = new HashSet<lote_produto>();
            this.movimentos_produtos_contabeis = new HashSet<movimentos_produtos_contabeis>();
            this.ordem_de_producao_resultado = new HashSet<ordem_de_producao_resultado>();
            this.solicitacao_de_amostra = new HashSet<solicitacao_de_amostra>();
            this.transferencia_entre_almoxarifado = new HashSet<transferencia_entre_almoxarifado>();
            this.transferencia_entre_almoxarifado1 = new HashSet<transferencia_entre_almoxarifado>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_BARRACAO { get; set; }
        public string CHAR_TIPO { get; set; }
        public string TXT_ENDERECO { get; set; }
        public Nullable<int> INT_X { get; set; }
        public Nullable<int> INT_Y { get; set; }
    
        public virtual ICollection<agendamento_carga_descarga> agendamento_carga_descarga { get; set; }
        public virtual ICollection<alas_do_armazem> alas_do_armazem { get; set; }
        public virtual ICollection<autorizacao_generica> autorizacao_generica { get; set; }
        public virtual ICollection<carregamento_para_armazem_terceiros> carregamento_para_armazem_terceiros { get; set; }
        public virtual ICollection<instrucao_preparo> instrucao_preparo { get; set; }
        public virtual ICollection<resultado_rebeneficio> resultado_rebeneficio { get; set; }
        public virtual ICollection<cadastro_entrada> cadastro_entrada { get; set; }
        public virtual ICollection<autorizacao_generica> autorizacao_generica1 { get; set; }
        public virtual ICollection<contrato> contrato { get; set; }
        public virtual ICollection<contrato> contrato1 { get; set; }
        public virtual ICollection<fechamento_mercado_futuro> fechamento_mercado_futuro { get; set; }
        public virtual ICollection<lote_produto> lote_produto { get; set; }
        public virtual ICollection<movimentos_produtos_contabeis> movimentos_produtos_contabeis { get; set; }
        public virtual ICollection<ordem_de_producao_resultado> ordem_de_producao_resultado { get; set; }
        public virtual ICollection<solicitacao_de_amostra> solicitacao_de_amostra { get; set; }
        public virtual ICollection<transferencia_entre_almoxarifado> transferencia_entre_almoxarifado { get; set; }
        public virtual ICollection<transferencia_entre_almoxarifado> transferencia_entre_almoxarifado1 { get; set; }
    }
}
