//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class amostra_da_roca
    {
        public int INT_ID { get; set; }
        public Nullable<int> INT_ID_COOPERADO { get; set; }
        public decimal DECIMAL_QTD_SACAS { get; set; }
        public System.DateTime DATE_ENTRADA { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public int INT_ID_FUNCIONARIO { get; set; }
        public Nullable<int> INT_ID_BEBIDA { get; set; }
        public bool BOOL_ORG_CONV { get; set; }
        public string TXT_LOTE { get; set; }
        public bool BOOL_TRANSICAO { get; set; }
        public Nullable<decimal> DECIMAL_TEOR_UMIDADE { get; set; }
        public string TXT_SAFRA { get; set; }
        public string TXT_REFERENCIA_PRODUTOR { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public string TXT_OBS { get; set; }
        public bool BOOL_AMOSTRA_TERCEIRO { get; set; }
        public string TXT_PRODUTOR { get; set; }
    
        public virtual bebida bebida { get; set; }
        public virtual cooperado cooperado { get; set; }
        public virtual funcionario funcionario { get; set; }
    }
}
