//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class amostra_solo_foliar_talhao
    {
        public int INT_ID { get; set; }
        public int INT_ID_AMOSTRA { get; set; }
        public int INT_ID_TALHAO { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual amostra_solo_foliar amostra_solo_foliar { get; set; }
        public virtual talhao talhao { get; set; }
    }
}
