//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class amostra_solo_foliar
    {
        public amostra_solo_foliar()
        {
            this.amostra_solo_foliar_lote = new HashSet<amostra_solo_foliar_lote>();
            this.amostra_solo_foliar_talhao = new HashSet<amostra_solo_foliar_talhao>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_OBS_AMOSTRA { get; set; }
        public System.DateTime DATE_CADASTRO { get; set; }
        public Nullable<System.DateTime> DATE_ALTEROU { get; set; }
        public Nullable<System.DateTime> DATE_EXCLUIU { get; set; }
        public int INT_ID_CADASTRO { get; set; }
        public Nullable<int> INT_ID_ALTEROU { get; set; }
        public Nullable<int> INT_ID_EXCLUIU { get; set; }
        public string TXT_STATUS { get; set; }
        public Nullable<System.DateTime> DATE_RESULTADO_ENTREGUE_COOPERADO_DATA { get; set; }
        public Nullable<int> INT_ID_RESULTADO_ENTREGUE_COOPERADO { get; set; }
        public int INT_ID_TIPO_AMOSTRA { get; set; }
        public int INT_ID_PRODUTOR { get; set; }
        public bool BOOL_TIPO_CULTIVO { get; set; }
        public decimal DECIMAL_ESTIMATIVA_SAFRA_PROXIMO_ANO { get; set; }
        public Nullable<System.DateTime> DATE_RECEBE_RESULTADO_AMOSTRA { get; set; }
        public Nullable<int> INT_ID_RECEBE_RESULTADO_AMOSTRA { get; set; }
        public string TXT_NUM_AMOSTRA { get; set; }
        public bool BOOL_CUSTEIO_COOPFAM { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public System.DateTime DATE_RECEBE_AMOSTRA { get; set; }
        public Nullable<int> INT_ID_AMOSTRA_CALCULADA { get; set; }
        public Nullable<System.DateTime> DATE_AMOSTRA_CALCULADA { get; set; }
    
        public virtual funcionario funcionario { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        public virtual funcionario funcionario2 { get; set; }
        public virtual funcionario funcionario3 { get; set; }
        public virtual cooperado cooperado { get; set; }
        public virtual funcionario funcionario4 { get; set; }
        public virtual funcionario funcionario5 { get; set; }
        public virtual tipo_amostra tipo_amostra { get; set; }
        public virtual ICollection<amostra_solo_foliar_lote> amostra_solo_foliar_lote { get; set; }
        public virtual ICollection<amostra_solo_foliar_talhao> amostra_solo_foliar_talhao { get; set; }
    }
}
