//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class autorizacao_generica
    {
        public autorizacao_generica()
        {
            this.autorizacao_dev_cooperado = new HashSet<autorizacao_dev_cooperado>();
            this.origem_do_produto = new HashSet<origem_do_produto>();
            this.autorizacao_lotes = new HashSet<autorizacao_lotes>();
            this.carregamento_para_armazem_terceiros = new HashSet<carregamento_para_armazem_terceiros>();
            this.autorizacao_venda_exp = new HashSet<autorizacao_venda_exp>();
            this.motorista_autorizacao = new HashSet<motorista_autorizacao>();
            this.movimentos_produtos_contabeis = new HashSet<movimentos_produtos_contabeis>();
            this.nota_fiscal = new HashSet<nota_fiscal>();
            this.ordem_de_producao = new HashSet<ordem_de_producao>();
            this.relacao_situacao_norma = new HashSet<relacao_situacao_norma>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_AUTORIZACAO { get; set; }
        public System.DateTime DATE_DATA_AUTORIZACAO { get; set; }
        public int INT_ID_AUTORIZADO { get; set; }
        public Nullable<int> INT_ID_ALMOXARIFADO_ORI { get; set; }
        public string TXT_SAFRA { get; set; }
        public bool BOOL_TIPO_CAFE { get; set; }
        public Nullable<int> INT_ID_SUBTIPO { get; set; }
        public Nullable<int> INT_ID_SITUACAONORMA { get; set; }
        public Nullable<int> INT_ID_FUNCIONARIO { get; set; }
        public string TXT_OBS { get; set; }
        public Nullable<int> INT_ID_CLIENTE { get; set; }
        public Nullable<int> INT_ID_CONTRATO { get; set; }
        public string CHAR_TIPO_AUTORIZACAO { get; set; }
        public Nullable<int> INT_ID_ALMOXARIFADO_DESTINO { get; set; }
        public bool BOOL_ATIVO_EXCLUIDO { get; set; }
        public Nullable<int> INT_ID_AMOSTRA { get; set; }
        public bool BOOL_INDUSTRIA { get; set; }
        public bool BOOL_INDUSTRIA_PARA_TERCEIRO { get; set; }
        public bool BOOL_ETIQUETA_SUPERSCKS { get; set; }
        public bool BOOL_FOORRACAO_SIMPLES { get; set; }
        public bool BOOL_AMOSTRA_COM_MOTORISTA { get; set; }
        public decimal DECIMAL_QTD_AMOSTRA { get; set; }
        public bool BOOL_LAUDO_COM_A_CARGA { get; set; }
        public bool BOOL_DECLARACAO_DE_AMOSTRA_AO_FISCAL_DO_MAPA { get; set; }
        public bool BOOL_FORRACAO_DUPLA { get; set; }
        public bool BOOL_DIFAL { get; set; }
        public bool BOOL_DAE { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public bool BOOL_FINALIZOU_CARREGAMENTO { get; set; }
        public Nullable<System.DateTime> DATE_INICIOU_CARREGAMENTO { get; set; }
        public Nullable<System.DateTime> DATE_FINALIZOU_CARREGAMENTO { get; set; }
        public Nullable<int> INT_ID_INICIOU_CARREGAMENTO { get; set; }
        public Nullable<int> INT_ID_FINALIZOU_CARREGAMENTO { get; set; }
        public Nullable<int> INT_ID_REVISAO_POP { get; set; }
        public bool BOOL_VINCULAR_NOTA_FILIAL { get; set; }
    
        public virtual almoxarifado almoxarifado { get; set; }
        public virtual almoxarifado almoxarifado1 { get; set; }
        public virtual ICollection<autorizacao_dev_cooperado> autorizacao_dev_cooperado { get; set; }
        public virtual composicao_amostra composicao_amostra { get; set; }
        public virtual ICollection<origem_do_produto> origem_do_produto { get; set; }
        public virtual ICollection<autorizacao_lotes> autorizacao_lotes { get; set; }
        public virtual ICollection<carregamento_para_armazem_terceiros> carregamento_para_armazem_terceiros { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        public virtual revisoes_pop revisoes_pop { get; set; }
        public virtual ICollection<autorizacao_venda_exp> autorizacao_venda_exp { get; set; }
        public virtual funcionario funcionario2 { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual contrato contrato { get; set; }
        public virtual funcionario funcionario3 { get; set; }
        public virtual ICollection<motorista_autorizacao> motorista_autorizacao { get; set; }
        public virtual ICollection<movimentos_produtos_contabeis> movimentos_produtos_contabeis { get; set; }
        public virtual ICollection<nota_fiscal> nota_fiscal { get; set; }
        public virtual ICollection<ordem_de_producao> ordem_de_producao { get; set; }
        public virtual ICollection<relacao_situacao_norma> relacao_situacao_norma { get; set; }
        public virtual situacao_norma situacao_norma { get; set; }
        public virtual subtipo_norma subtipo_norma { get; set; }
    }
}
