//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class bolsa
    {
        public bolsa()
        {
            this.hedge = new HashSet<hedge>();
            this.rolagem = new HashSet<rolagem>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_BOLSA { get; set; }
        public decimal DECIMAL_FATOR_DE_CONVERSAO { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual ICollection<hedge> hedge { get; set; }
        public virtual ICollection<rolagem> rolagem { get; set; }
    }
}
