//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoria_de_emprestimo
    {
        public categoria_de_emprestimo()
        {
            this.emprestimos = new HashSet<emprestimos>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_CATEGORIA { get; set; }
        public string CHAR_MODELO_DE_CONTRATO { get; set; }
        public Nullable<int> INT_ID_PLANEJAMENTO { get; set; }
        public Nullable<bool> BOOL_FT_OUTRAS_FONTES { get; set; }
    
        public virtual planejamento planejamento { get; set; }
        public virtual ICollection<emprestimos> emprestimos { get; set; }
    }
}
