//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class cepbr_estado
    {
        public cepbr_estado()
        {
            this.cepbr_cidade = new HashSet<cepbr_cidade>();
        }
    
        public string uf { get; set; }
        public string estado { get; set; }
        public string cod_ibge { get; set; }
    
        public virtual ICollection<cepbr_cidade> cepbr_cidade { get; set; }
    }
}
