//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class cepbr_enderecos
    {
        public cepbr_enderecos()
        {
            this.cliente = new HashSet<cliente>();
            this.cooperado = new HashSet<cooperado>();
            this.propriedade = new HashSet<propriedade>();
        }
    
        public string TXT_CEP { get; set; }
        public string TXT_LOGRADOURO { get; set; }
        public string TXT_TIPO_LOGRADOURO { get; set; }
        public string TXT_COMPLEMENTO { get; set; }
        public string TXT_LOCAL { get; set; }
        public Nullable<int> INT_ID_CIDADE { get; set; }
        public Nullable<int> INT_ID_BAIRRO { get; set; }
        public int INT_ID { get; set; }
    
        public virtual cepbr_bairro cepbr_bairro { get; set; }
        public virtual cepbr_cidade cepbr_cidade { get; set; }
        public virtual ICollection<cliente> cliente { get; set; }
        public virtual ICollection<cooperado> cooperado { get; set; }
        public virtual ICollection<propriedade> propriedade { get; set; }
    }
}
