//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class certificacao
    {
        public certificacao()
        {
            this.criterios = new HashSet<criterios>();
            this.formulario = new HashSet<formulario>();
            this.norma = new HashSet<norma>();
            this.ponto_critico = new HashSet<ponto_critico>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_DESCRICAO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public int INT_ID_EMPRESA { get; set; }
    
        public virtual empresa empresa { get; set; }
        public virtual ICollection<criterios> criterios { get; set; }
        public virtual ICollection<formulario> formulario { get; set; }
        public virtual ICollection<norma> norma { get; set; }
        public virtual ICollection<ponto_critico> ponto_critico { get; set; }
    }
}
