//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfop
    {
        public cfop()
        {
            this.movimentos_produtos_contabeis = new HashSet<movimentos_produtos_contabeis>();
            this.nota_fiscal = new HashSet<nota_fiscal>();
            this.padrao_de_imposto_por_cfop = new HashSet<padrao_de_imposto_por_cfop>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_CFOP { get; set; }
        public string TXT_NATUREZA { get; set; }
        public bool BOOL_REFERENCIADA { get; set; }
        public int INT_ID_EMPRESA { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public bool BOOL_DOACAO { get; set; }
    
        public virtual empresa empresa { get; set; }
        public virtual ICollection<movimentos_produtos_contabeis> movimentos_produtos_contabeis { get; set; }
        public virtual ICollection<nota_fiscal> nota_fiscal { get; set; }
        public virtual ICollection<padrao_de_imposto_por_cfop> padrao_de_imposto_por_cfop { get; set; }
    }
}
