//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente_conta_bancaria
    {
        public cliente_conta_bancaria()
        {
            this.movimento_bancario = new HashSet<movimento_bancario>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_CLIENTE { get; set; }
        public string TXT_BANCO { get; set; }
        public string TXT_AGENCIA { get; set; }
        public Nullable<bool> BOOL_CONTA_CORRENTE_POUPANCA { get; set; }
        public string TXT_CONTA { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public string TXT_CODIGO_BANCO { get; set; }
        public string TXT_CIDADE { get; set; }
        public string TXT_UF { get; set; }
        public Nullable<bool> BOOL_CONTA_CONJUNTA { get; set; }
        public string TXT_TITULAR { get; set; }
        public string TXT_CHAVE_PIX { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual ICollection<movimento_bancario> movimento_bancario { get; set; }
    }
}
