//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class comercial_ativo
    {
        public int INT_ID { get; set; }
        public Nullable<int> INT_ID_CLIENTE { get; set; }
        public int INT_ID_GRUPO_DE_SERVICO { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public int INT_ID_FUNCIONARIO { get; set; }
        public System.DateTime DATE_CONTATO { get; set; }
        public Nullable<System.DateTime> DATE_PROXIMO_CONTATO { get; set; }
        public bool BOOL_POTENCIAL_CLIENTE { get; set; }
        public string TXT_CLIENTE { get; set; }
        public string TXT_CONTATO { get; set; }
        public string TXT_DESCRICAO_DO_CONTATO { get; set; }
        public bool BOOL_CONVERSAO_EM_CLIENTE { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public int INT_ID_TIPO_CONTATO { get; set; }
        public int INT_ID_EMPRESA { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual grupo_de_servico grupo_de_servico { get; set; }
        public virtual tipo_de_contato_com_cliente tipo_de_contato_com_cliente { get; set; }
    }
}
