//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class complementacao
    {
        public complementacao()
        {
            this.complementacoes_lote = new HashSet<complementacoes_lote>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_MOTIVO { get; set; }
        public string TXT_OBS { get; set; }
        public System.DateTime DATE { get; set; }
        public int INT_ID_COOPERADO { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual cooperado cooperado { get; set; }
        public virtual ICollection<complementacoes_lote> complementacoes_lote { get; set; }
    }
}
