//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class composicao_amostra
    {
        public composicao_amostra()
        {
            this.autorizacao_generica = new HashSet<autorizacao_generica>();
            this.instrucao_preparo = new HashSet<instrucao_preparo>();
            this.composicao_amostra_envio = new HashSet<composicao_amostra_envio>();
            this.lote_composicao = new HashSet<lote_composicao>();
            this.relacao_situacao_norma = new HashSet<relacao_situacao_norma>();
        }
    
        public int INT_ID { get; set; }
        public Nullable<int> INT_ID_CLIENTE { get; set; }
        public Nullable<int> INT_ID_CONTRATO { get; set; }
        public Nullable<bool> BOOL_FLAG_APROVADA_REPROVADA { get; set; }
        public string CHAR_STATUS_AMOSTRA { get; set; }
        public Nullable<System.DateTime> DATE_ENVIO { get; set; }
        public Nullable<System.DateTime> DATE_APROVACAO_REP { get; set; }
        public string TXT_OBS { get; set; }
        public Nullable<int> INT_ID_SITUACAO_NORMA { get; set; }
        public Nullable<float> FLOAT_POR_CENTAGEM_DE_PENEIRA_18 { get; set; }
        public Nullable<float> FLOAT_POR_CENTAGEM_DE_PENEIRA_17 { get; set; }
        public Nullable<float> FLOAT_POR_CENTAGEM_DE_PENEIRA_16 { get; set; }
        public Nullable<float> FLOAT_POR_CENTAGEM_DE_PENEIRA_MK { get; set; }
        public Nullable<float> FLOAT_POR_CENTAGEM_DE_PENEIRA_15 { get; set; }
        public Nullable<float> FLOAT_POR_CENTAGEM_DE_PENEIRA_14 { get; set; }
        public Nullable<float> FLOAT_POR_CENTAGEM_DE_PENEIRA_13 { get; set; }
        public Nullable<float> FLOAT_POR_CENTAGEM_DE_PENEIRA_FUNDO { get; set; }
        public Nullable<System.DateTime> DATE_QUE_AMOSTRA_FOI_RECEBIDA { get; set; }
        public string TXT_SAFRA { get; set; }
        public string TXT_CODIGO_RASTREIO { get; set; }
        public Nullable<int> INT_ID_SUBTIPO_NORMA { get; set; }
        public bool BOOL_ORG_CONV { get; set; }
        public string TXT_ONDE_FOI_POSTADO { get; set; }
        public string TXT_REFERENCIA_AMOSTRA { get; set; }
        public Nullable<int> INT_NF { get; set; }
        public Nullable<System.DateTime> DATA_CONFECCAO { get; set; }
    
        public virtual ICollection<autorizacao_generica> autorizacao_generica { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual ICollection<instrucao_preparo> instrucao_preparo { get; set; }
        public virtual ICollection<composicao_amostra_envio> composicao_amostra_envio { get; set; }
        public virtual ICollection<lote_composicao> lote_composicao { get; set; }
        public virtual contrato contrato { get; set; }
        public virtual ICollection<relacao_situacao_norma> relacao_situacao_norma { get; set; }
        public virtual situacao_norma situacao_norma { get; set; }
        public virtual subtipo_norma subtipo_norma { get; set; }
    }
}
