//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class conciliacoes
    {
        public int INT_ID { get; set; }
        public System.DateTime DATE_CONCILIADO { get; set; }
        public string CHAR_TIPO_CONCILIACAO { get; set; }
        public int INT_ID_EMPRESA { get; set; }
    
        public virtual empresa empresa { get; set; }
    }
}
