//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracoes
    {
        public int INT_ID { get; set; }
        public string TXT_CAMINHO_FOTO { get; set; }
        public string TXT_CAMINHO_PDF { get; set; }
        public string TXT_CAMINHO_EVIDENCIAS { get; set; }
        public string TXT_REDUCAO_TEMPO_TRANSICAO { get; set; }
    }
}
