//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracao_nota_filial
    {
        public configuracao_nota_filial()
        {
            this.nota_fiscal = new HashSet<nota_fiscal>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_REMESSA_EMPRESA { get; set; }
        public int INT_ID_RETORNO_EMPRESA { get; set; }
        public int INT_ID_CFOP { get; set; }
        public bool BOOL_ENTRADA_SAIDA { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public System.DateTime DATE_EXCLUIU { get; set; }
        public int INT_ID_PRODUTO { get; set; }
        public decimal DECIMAL_VLR_UNITARIO { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual padrao_de_imposto_por_cfop padrao_de_imposto_por_cfop { get; set; }
        public virtual produtos_contabeis produtos_contabeis { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual empresa empresa1 { get; set; }
        public virtual ICollection<nota_fiscal> nota_fiscal { get; set; }
    }
}
