//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrato
    {
        public contrato()
        {
            this.agendamento_carga_descarga = new HashSet<agendamento_carga_descarga>();
            this.autorizacao_generica = new HashSet<autorizacao_generica>();
            this.composicao_amostra = new HashSet<composicao_amostra>();
            this.contas_a_pagar_despesas_contrato = new HashSet<contas_a_pagar_despesas_contrato>();
            this.instrucao_preparo = new HashSet<instrucao_preparo>();
            this.origem_do_produto = new HashSet<origem_do_produto>();
            this.referencia_hedge = new HashSet<referencia_hedge>();
            this.fluxo_de_caixa = new HashSet<fluxo_de_caixa>();
            this.liquidacao_contrato_de_cambio = new HashSet<liquidacao_contrato_de_cambio>();
            this.premio_ft = new HashSet<premio_ft>();
            this.relacao_situacao_norma = new HashSet<relacao_situacao_norma>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_CLIENTE { get; set; }
        public string TXT_CONTRATO { get; set; }
        public string TXT_SAFRA { get; set; }
        public Nullable<int> INT_ID_BEBIDA { get; set; }
        public Nullable<float> FLOAT_PONTUACAO { get; set; }
        public string TXT_TIPO { get; set; }
        public System.DateTime DATE_ENTREGA { get; set; }
        public Nullable<int> INT_DEFEITOS { get; set; }
        public Nullable<int> INT_ID_SITUACAONORMA { get; set; }
        public string TXT_OBS { get; set; }
        public string TXT_OIC { get; set; }
        public string TXT_TIPO_SACARIA { get; set; }
        public string TXT_PENEIRA { get; set; }
        public string TXT_INVOICE { get; set; }
        public Nullable<decimal> INT_QTD_SACAS { get; set; }
        public Nullable<float> FLOAT_PESO_LIQUIDO { get; set; }
        public decimal FLOAT_DIFERENCIAL { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public Nullable<int> INT_NF { get; set; }
        public Nullable<System.DateTime> DATE_FECHAMENTO { get; set; }
        public Nullable<bool> BOOL_AFIXAR { get; set; }
        public Nullable<float> FLOAT_PRECO { get; set; }
        public Nullable<int> INT_SUBTIPO_NORMA { get; set; }
        public bool BOOL_TIPO_CAFE { get; set; }
        public Nullable<System.DateTime> DATE_DATA_MAXIMA_ENTREGA_DA_AMOSTRA { get; set; }
        public decimal FLOAT_DOLAR { get; set; }
        public decimal FLOAT_NY { get; set; }
        public Nullable<System.DateTime> DATE_ENTREGA_AMOSTRA { get; set; }
        public bool BOOL_A_FIXAR_DOLAR { get; set; }
        public Nullable<bool> BOOL_FT_NFT { get; set; }
        public string TXT_COM_HEDGE_PRECO_MINIMO_INFERIOR { get; set; }
        public decimal FLOAT_QTD_COMPRADA_PRECO_MINIMO { get; set; }
        public decimal DECIMAL_SCS_VENDIDAS_FT { get; set; }
        public string TXT_REFERENCIA_DO_COMPRADOR { get; set; }
        public decimal DECIMAL_TOTAL_EM_DOLAR_DO_CONTRATO { get; set; }
        public Nullable<int> INT_ID_ALMOXARIFADO { get; set; }
        public Nullable<int> INT_ID_TRANSPORTADORA { get; set; }
        public string TXT_OBS_LOGISTICA { get; set; }
        public string TXT_OBS_CLASSIFICACAO { get; set; }
        public Nullable<int> INT_ID_PENEIRA { get; set; }
        public Nullable<int> INT_ID_SACARIA { get; set; }
        public Nullable<int> INT_ID_TIPO { get; set; }
        public Nullable<int> INT_ID_MODALIDADE_DE_ENTREGA { get; set; }
        public Nullable<System.DateTime> DATE_AGENDADO_EMBARQUE { get; set; }
        public Nullable<System.DateTime> DATE_DE_FECHAMENTO_DO_CONTRATO { get; set; }
        public Nullable<int> INT_ID_FORMA_PAGAMENTO { get; set; }
        public Nullable<System.DateTime> DATE_LIMITE_EMBARQUE { get; set; }
        public Nullable<System.DateTime> DATE_VENCIMENTO_PARA_HEDGE { get; set; }
        public string TXT_DESTINO { get; set; }
        public string TXT_DESCRICAO_QUALIDADE { get; set; }
        public string TXT_DESCRICAO_PRECO { get; set; }
        public Nullable<bool> BOOL_SEGURO { get; set; }
        public string TXT_OBS_INGLES { get; set; }
        public Nullable<int> INT_ID_PRE_FINANCIAMENTO { get; set; }
        public Nullable<int> INT_ID_GESTAO_RISCO { get; set; }
        public Nullable<int> INT_ID_ARBITRAGEM { get; set; }
        public Nullable<int> INT_ID_TIPO_DE_TERMO_CONDICAO { get; set; }
        public Nullable<int> INT_ID_PAPEL_DAS_PARTES { get; set; }
        public Nullable<int> INT_ID_LOCAL_DE_EMBARQUE { get; set; }
    
        public virtual ICollection<agendamento_carga_descarga> agendamento_carga_descarga { get; set; }
        public virtual almoxarifado almoxarifado { get; set; }
        public virtual almoxarifado almoxarifado1 { get; set; }
        public virtual arbitragem_cafe arbitragem_cafe { get; set; }
        public virtual ICollection<autorizacao_generica> autorizacao_generica { get; set; }
        public virtual bebida bebida { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual ICollection<composicao_amostra> composicao_amostra { get; set; }
        public virtual ICollection<contas_a_pagar_despesas_contrato> contas_a_pagar_despesas_contrato { get; set; }
        public virtual forma_de_pagamento forma_de_pagamento { get; set; }
        public virtual gestao_risco gestao_risco { get; set; }
        public virtual ICollection<instrucao_preparo> instrucao_preparo { get; set; }
        public virtual modalidade_entrega modalidade_entrega { get; set; }
        public virtual ICollection<origem_do_produto> origem_do_produto { get; set; }
        public virtual papel_das_partes_contrato_cafe papel_das_partes_contrato_cafe { get; set; }
        public virtual tipo_lote_rebeneficio_para_gerar tipo_lote_rebeneficio_para_gerar { get; set; }
        public virtual pre_financiamento pre_financiamento { get; set; }
        public virtual tipo_sacaria tipo_sacaria { get; set; }
        public virtual tipo_cafe_rebeneficiado tipo_cafe_rebeneficiado { get; set; }
        public virtual termo_e_condicao_contrato_cafe_cru termo_e_condicao_contrato_cafe_cru { get; set; }
        public virtual motorista motorista { get; set; }
        public virtual ICollection<referencia_hedge> referencia_hedge { get; set; }
        public virtual ICollection<fluxo_de_caixa> fluxo_de_caixa { get; set; }
        public virtual ICollection<liquidacao_contrato_de_cambio> liquidacao_contrato_de_cambio { get; set; }
        public virtual ICollection<premio_ft> premio_ft { get; set; }
        public virtual ICollection<relacao_situacao_norma> relacao_situacao_norma { get; set; }
        public virtual situacao_norma situacao_norma { get; set; }
        public virtual subtipo_norma subtipo_norma { get; set; }
    }
}
