//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class contas_bancarias_empresa
    {
        public contas_bancarias_empresa()
        {
            this.acc_com_hedge = new HashSet<acc_com_hedge>();
            this.movimento_bancario = new HashSet<movimento_bancario>();
            this.tipo_de_pagamento = new HashSet<tipo_de_pagamento>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_BANCO { get; set; }
        public string TXT_AGENCIA { get; set; }
        public string TXT_CONTA { get; set; }
        public string TXT_CODIGO_BANCO { get; set; }
        public bool BOOL_CORRENTE_POUPANCAO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public bool BOOL_CONTA_BANCARIA_CONTA_CAIXA { get; set; }
        public decimal DECIMAL_SALDO_INICIAL { get; set; }
        public Nullable<int> INT_ID_CONTA_CONTABIL { get; set; }
    
        public virtual ICollection<acc_com_hedge> acc_com_hedge { get; set; }
        public virtual plano_de_contas_contabil plano_de_contas_contabil { get; set; }
        public virtual ICollection<movimento_bancario> movimento_bancario { get; set; }
        public virtual ICollection<tipo_de_pagamento> tipo_de_pagamento { get; set; }
    }
}
