//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class contas_a_pagar_planejamento
    {
        public int INT_ID { get; set; }
        public int INT_ID_PLANEJAMENTO { get; set; }
        public Nullable<int> INT_ID_CONTAS_A_PAGAR { get; set; }
        public decimal DECIMAL_VALOR_FT { get; set; }
        public decimal DECIMAL_VALOR_EMPRESA { get; set; }
        public bool BOOL_ADIANTAMENTO { get; set; }
        public Nullable<int> INT_ID_MOVIMENTO_BANCARIO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public Nullable<int> INT_ID_EMPRESTIMO { get; set; }
        public bool BOOL_MIGROU_PREMIO_FT { get; set; }
    
        public virtual contas_a_pagar_e_receber contas_a_pagar_e_receber { get; set; }
        public virtual emprestimos emprestimos { get; set; }
        public virtual movimento_bancario movimento_bancario { get; set; }
        public virtual planejamento planejamento { get; set; }
    }
}
