//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class convenio_plano_de_saude
    {
        public convenio_plano_de_saude()
        {
            this.procedimento = new HashSet<procedimento>();
            this.tabela_codigo_produto_por_convenio = new HashSet<tabela_codigo_produto_por_convenio>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_DESCRICAO { get; set; }
        public string CHAR_TIPO { get; set; }
        public Nullable<int> INT_ID_CLIENTE { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public string TXT_CODIGO_NA_OPERADORA { get; set; }
        public string TXT_REG_ANS { get; set; }
        public int INT_ID_EMPRESA { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual ICollection<procedimento> procedimento { get; set; }
        public virtual ICollection<tabela_codigo_produto_por_convenio> tabela_codigo_produto_por_convenio { get; set; }
    }
}
