//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class convenio_medico_guia
    {
        public int INT_ID { get; set; }
        public int INT_ID_CONVENIO { get; set; }
        public int INT_ID_TIPO_PROCEDIMENTO { get; set; }
        public int INT_ID_PARTICIPANTE { get; set; }
        public bool BOOL_TITULAR { get; set; }
        public Nullable<int> INT_ID_DEPENDENTE { get; set; }
        public string TXT_GUIA { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public string TXT_MEDICO { get; set; }
        public string TXT_LOCAL { get; set; }
        public string TXT_OBS { get; set; }
        public System.DateTime DATE_PROCEDIMENTO { get; set; }
        public string TXT_PROCEDIMENTO { get; set; }
        public bool BOOL_REALIZADO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public decimal DECIMAL_VALOR { get; set; }
        public decimal DECIMAL_PERCENTUAL { get; set; }
        public decimal DECIMAL_CONTRAPARTIDA { get; set; }
        public int INT_ID_LANCOU { get; set; }
        public Nullable<int> INT_ID_ULTIMA_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DATE_ULTIMA_ALTERACAO { get; set; }
        public Nullable<int> INT_ID_EXCLUIU { get; set; }
        public Nullable<System.DateTime> DATE_EXCLUIU { get; set; }
        public bool BOOL_RETORNO { get; set; }
    
        public virtual convenio_medico convenio_medico { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual dependentes_plano_de_saude dependentes_plano_de_saude { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        public virtual funcionario funcionario2 { get; set; }
        public virtual convenio_titular convenio_titular { get; set; }
        public virtual tipo_de_procedimento tipo_de_procedimento { get; set; }
    }
}
