//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class convenio_titular
    {
        public convenio_titular()
        {
            this.convenio_medico_guia = new HashSet<convenio_medico_guia>();
            this.dependentes_plano_de_saude = new HashSet<dependentes_plano_de_saude>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_CONVENIO { get; set; }
        public Nullable<int> INT_ID_COOPERADO { get; set; }
        public Nullable<int> INT_ID_COLABORADOR { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual convenio_medico convenio_medico { get; set; }
        public virtual ICollection<convenio_medico_guia> convenio_medico_guia { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual cooperado cooperado { get; set; }
        public virtual ICollection<dependentes_plano_de_saude> dependentes_plano_de_saude { get; set; }
    }
}
