//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class cooperado_que_fazem_parte_do_mercado_futuro
    {
        public cooperado_que_fazem_parte_do_mercado_futuro()
        {
            this.agendamento_cooperado = new HashSet<agendamento_cooperado>();
            this.cooperado_que_fazem_parte_do_mercado_futura_situacao_norma = new HashSet<cooperado_que_fazem_parte_do_mercado_futura_situacao_norma>();
            this.lotes_do_fechamento_e_hedge = new HashSet<lotes_do_fechamento_e_hedge>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_COOPERADO { get; set; }
        public decimal FLOAT_CATACAO { get; set; }
        public decimal FLOAT_QTD_SACAS_BICA { get; set; }
        public decimal FLOAT_QTD_SACAS_BOAS { get; set; }
        public int INT_ID_FECHAMENTO_MERCADO_FUTURO { get; set; }
        public string TXT_OBS { get; set; }
        public decimal FLOAT_VALOR_MINIMO { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public int INT_ID_FUNC { get; set; }
        public bool BOOL_ORG_CONV { get; set; }
        public Nullable<System.DateTime> DATE_MAXIMA_PARA_ENTREGA { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public bool BOOL_EM_TRANSICAO { get; set; }
        public Nullable<System.DateTime> DATE_PAGAMENTO { get; set; }
        public Nullable<decimal> DECIMAL_PRECO_EM_REAIS { get; set; }
        public Nullable<decimal> DECIMAL_PENEIRA1415 { get; set; }
        public Nullable<decimal> DECIMAL_PENEIRA16UP { get; set; }
        public Nullable<System.DateTime> DATE_GEROU_CONTRATO { get; set; }
        public Nullable<int> INT_ID_CONTA_PARA_PAGAMENTO { get; set; }
        public Nullable<int> INT_ID_ALTEROU { get; set; }
        public Nullable<System.DateTime> DATE_ALTEROU { get; set; }
        public Nullable<int> INT_ID_EXCLUIU { get; set; }
        public Nullable<System.DateTime> DATE_EXCLUIU { get; set; }
        public decimal DECIMAL_SCS_WASH_OUT { get; set; }
    
        public virtual ICollection<agendamento_cooperado> agendamento_cooperado { get; set; }
        public virtual cooperado cooperado { get; set; }
        public virtual ICollection<cooperado_que_fazem_parte_do_mercado_futura_situacao_norma> cooperado_que_fazem_parte_do_mercado_futura_situacao_norma { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual dados_bancarios dados_bancarios { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        public virtual fechamento_mercado_futuro fechamento_mercado_futuro { get; set; }
        public virtual funcionario funcionario2 { get; set; }
        public virtual ICollection<lotes_do_fechamento_e_hedge> lotes_do_fechamento_e_hedge { get; set; }
    }
}
