//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotacao_compra
    {
        public cotacao_compra()
        {
            this.contas_a_pagar_e_receber = new HashSet<contas_a_pagar_e_receber>();
            this.cotacao_compra_item = new HashSet<cotacao_compra_item>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_OBS { get; set; }
        public string TXT_NUM_PEDIDO { get; set; }
        public System.DateTime DATE_CADASTRO { get; set; }
        public int INT_ID_CADASTRO { get; set; }
        public Nullable<int> INT_ID_ALTERA { get; set; }
        public Nullable<System.DateTime> DATE_ALTERA { get; set; }
        public Nullable<int> INT_ID_EXCLUI { get; set; }
        public Nullable<System.DateTime> DATE_EXCLUI { get; set; }
        public Nullable<int> IND_ID_FORMA_PAGAMENTO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public int INT_ID_FORNECEDOR { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual ICollection<contas_a_pagar_e_receber> contas_a_pagar_e_receber { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        public virtual funcionario funcionario2 { get; set; }
        public virtual forma_de_pagamento forma_de_pagamento { get; set; }
        public virtual ICollection<cotacao_compra_item> cotacao_compra_item { get; set; }
    }
}
