//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class curso
    {
        public curso()
        {
            this.curso_realizados = new HashSet<curso_realizados>();
            this.curso_relacionado = new HashSet<curso_relacionado>();
            this.curso_relacionado1 = new HashSet<curso_relacionado>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_CURSO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public int INT_ID_EMPRESA { get; set; }
        public bool BOOL_OBRIGATRIO { get; set; }
        public string TXT_CRITERIO { get; set; }
    
        public virtual ICollection<curso_realizados> curso_realizados { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual ICollection<curso_relacionado> curso_relacionado { get; set; }
        public virtual ICollection<curso_relacionado> curso_relacionado1 { get; set; }
    }
}
