//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class curso_relacionado
    {
        public int INT_ID { get; set; }
        public int INT_ID_CURSO_PRINCIPAL { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public int INT_ID_CURSO_SELECIONADO { get; set; }
    
        public virtual curso curso { get; set; }
        public virtual curso curso1 { get; set; }
    }
}
