//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class curso_ministrantes
    {
        public curso_ministrantes()
        {
            this.curso_realizados = new HashSet<curso_realizados>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_MINISTRANTE { get; set; }
        public string TXT_INSTITUICAO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public int INT_ID_EMPRESA { get; set; }
    
        public virtual ICollection<curso_realizados> curso_realizados { get; set; }
    }
}
