//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class dependentes_plano_de_saude
    {
        public dependentes_plano_de_saude()
        {
            this.convenio_medico_guia = new HashSet<convenio_medico_guia>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_NOME { get; set; }
        public string TXT_CPF { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public int INT_ID_LANCOU { get; set; }
        public Nullable<System.DateTime> DATE_EXCLUSAO { get; set; }
        public Nullable<int> INT_ID_EXCLUIU { get; set; }
        public int INT_ID_TITULAR { get; set; }
        public Nullable<int> INT_ID_GRAU_DE_DEPENCIA { get; set; }
    
        public virtual ICollection<convenio_medico_guia> convenio_medico_guia { get; set; }
        public virtual convenio_titular convenio_titular { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual grau_de_parentesco grau_de_parentesco { get; set; }
        public virtual funcionario funcionario1 { get; set; }
    }
}
