//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class descontos_acrescimos_pg_cafe
    {
        public descontos_acrescimos_pg_cafe()
        {
            this.relacao_de_notas_desc_acrescimo = new HashSet<relacao_de_notas_desc_acrescimo>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_COOPERDO { get; set; }
        public int INT_ID_FUNC { get; set; }
        public string TXT_MOTIVO { get; set; }
        public decimal DECIMAL_VALOR { get; set; }
        public decimal DECIMAL_SALDO { get; set; }
        public System.DateTime DATE_CALCULO { get; set; }
        public Nullable<System.DateTime> DATE_PG { get; set; }
        public string TXT_OBS { get; set; }
        public bool BOOL_DESC_ACRESCIMO { get; set; }
        public bool BOOL_DESC_CAFE { get; set; }
        public string TXT_DOC_SE_N_DESC_CAFE { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public Nullable<int> INT_ID_PARCELA { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public bool BOOL_DESCONTAR_AVALISTA { get; set; }
    
        public virtual cooperado cooperado { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual parcela_emprestimo parcela_emprestimo { get; set; }
        public virtual ICollection<relacao_de_notas_desc_acrescimo> relacao_de_notas_desc_acrescimo { get; set; }
    }
}
