//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class despesas_realizadas_contas_a_pg_e_rec
    {
        public int INT_ID { get; set; }
        public int INT_ID_CONTAS_A_PG_E_REC { get; set; }
        public int INT_ID_PRODUTO { get; set; }
        public decimal DECIMAL_QTD { get; set; }
        public decimal DECIMAL_VLR_UN { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual contas_a_pagar_e_receber contas_a_pagar_e_receber { get; set; }
        public virtual produtos_contabeis produtos_contabeis { get; set; }
    }
}
