//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class devolucao_de_compra
    {
        public devolucao_de_compra()
        {
            this.movimentos_produtos_contabeis = new HashSet<movimentos_produtos_contabeis>();
        }
    
        public int INT_ID { get; set; }
        public Nullable<int> INT_ID_LOTES_DO_FECHAMENTO { get; set; }
        public Nullable<int> INT_ID_NOTA_DE_ORIGEM { get; set; }
        public Nullable<int> INT_ID_COMPLEMENTACAO { get; set; }
        public decimal DECIMAL_QTD { get; set; }
        public Nullable<decimal> DECIMAL_VALOR_TOTAL_COMPRA { get; set; }
        public Nullable<decimal> DECIMAL_VALOR_CREDITO { get; set; }
        public Nullable<decimal> DECIMAL_VALOR_DEPOSITO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public int INT_ID_LANCAMENTO { get; set; }
        public Nullable<System.DateTime> DATE_ULTIMA_ALTERACAO { get; set; }
        public Nullable<int> INT_ID_ULTIMA_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DATE_EXCLUIU { get; set; }
        public Nullable<int> INT_ID_EXCLUIU { get; set; }
        public string TXT_OBS { get; set; }
        public Nullable<int> INT_NF_DEV_COMPRA { get; set; }
        public Nullable<int> INT_NF_ESTORNO_CREDITO { get; set; }
        public Nullable<int> INT_NF_DEPOSITO { get; set; }
        public Nullable<System.DateTime> DATE_ESTORNO_CREDITO { get; set; }
        public Nullable<System.DateTime> DATE_DEVOLUCAO { get; set; }
        public Nullable<System.DateTime> DATE_DEPOSITO { get; set; }
    
        public virtual complementacoes_lote complementacoes_lote { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        public virtual funcionario funcionario2 { get; set; }
        public virtual lotes_do_fechamento_e_hedge lotes_do_fechamento_e_hedge { get; set; }
        public virtual notas_de_origem notas_de_origem { get; set; }
        public virtual ICollection<movimentos_produtos_contabeis> movimentos_produtos_contabeis { get; set; }
    }
}
