//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa_forn_prod_agricola
    {
        public empresa_forn_prod_agricola()
        {
            this.formulario_item_selecao = new HashSet<formulario_item_selecao>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_EMPRESA { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual ICollection<formulario_item_selecao> formulario_item_selecao { get; set; }
    }
}
