//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        public empresa()
        {
            this.acc_com_hedge = new HashSet<acc_com_hedge>();
            this.bebida_padrao = new HashSet<bebida_padrao>();
            this.certificacao = new HashSet<certificacao>();
            this.cfop = new HashSet<cfop>();
            this.comercial_ativo = new HashSet<comercial_ativo>();
            this.conciliacoes = new HashSet<conciliacoes>();
            this.configuracao_nota_filial = new HashSet<configuracao_nota_filial>();
            this.configuracao_nota_filial1 = new HashSet<configuracao_nota_filial>();
            this.contas_a_pagar_e_receber = new HashSet<contas_a_pagar_e_receber>();
            this.convenio_medico = new HashSet<convenio_medico>();
            this.convenio_plano_de_saude = new HashSet<convenio_plano_de_saude>();
            this.curso = new HashSet<curso>();
            this.defeito_cafe = new HashSet<defeito_cafe>();
            this.funcionario = new HashSet<funcionario>();
            this.grupo_de_imposto = new HashSet<grupo_de_imposto>();
            this.grupo_de_servico = new HashSet<grupo_de_servico>();
            this.informacao_adicional = new HashSet<informacao_adicional>();
            this.produto_linha = new HashSet<produto_linha>();
            this.lote_produto = new HashSet<lote_produto>();
            this.maquinario = new HashSet<maquinario>();
            this.modalidade_entrega = new HashSet<modalidade_entrega>();
            this.movimentos_produtos_contabeis = new HashSet<movimentos_produtos_contabeis>();
            this.nota_fiscal = new HashSet<nota_fiscal>();
            this.ordem_de_producao = new HashSet<ordem_de_producao>();
            this.ordem_de_producao_resultado = new HashSet<ordem_de_producao_resultado>();
            this.pedido_faturamento = new HashSet<pedido_faturamento>();
            this.pilar = new HashSet<pilar>();
            this.planejamento_categoria = new HashSet<planejamento_categoria>();
            this.planejamento_item = new HashSet<planejamento_item>();
            this.plano_de_contas_contabil = new HashSet<plano_de_contas_contabil>();
            this.procedimento_tipo = new HashSet<procedimento_tipo>();
            this.rfid_chip = new HashSet<rfid_chip>();
            this.tabela_icms = new HashSet<tabela_icms>();
            this.tipo_cafe_rebeneficiado = new HashSet<tipo_cafe_rebeneficiado>();
            this.tipo_de_contato_com_cliente = new HashSet<tipo_de_contato_com_cliente>();
            this.tipo_de_permissao_alas_do_armazem = new HashSet<tipo_de_permissao_alas_do_armazem>();
            this.tipo_de_procedimento = new HashSet<tipo_de_procedimento>();
            this.tipo_lote_rebeneficio_para_gerar = new HashSet<tipo_lote_rebeneficio_para_gerar>();
            this.tipo_sacaria = new HashSet<tipo_sacaria>();
            this.transferencia_entre_almoxarifado = new HashSet<transferencia_entre_almoxarifado>();
            this.venda_prestacao_servico = new HashSet<venda_prestacao_servico>();
        }
    
        public int INT_ID_EMPRESA { get; set; }
        public string TXT_NOME_FANTASIA { get; set; }
        public string TXT_RAZAO_SOCIAL { get; set; }
        public string TXT_IE { get; set; }
        public string TXT_IM { get; set; }
        public string TXT_RUA { get; set; }
        public string TXT_NR { get; set; }
        public string TXT_BAIRRO { get; set; }
        public string TXT_MUNICIPIO { get; set; }
        public string TXT_UF { get; set; }
        public int INT_COD_PAIS_IBGE { get; set; }
        public int INT_COD_CIDADE_IBGE { get; set; }
        public string TXT_CNPJ { get; set; }
        public string TXT_PAIS { get; set; }
        public string TXT_TELEFONE { get; set; }
        public int INT_CRT { get; set; }
        public int INT_COD_UF { get; set; }
        public string TXT_CEP { get; set; }
        public string TXT_TOKEN_IBPT { get; set; }
        public string TXT_TOKEN_NFEMAIL { get; set; }
        public decimal DECIMAL_VALOR_DO_PREMIO_FAIR_TRADE { get; set; }
        public bool BOOL_CAFE { get; set; }
        public bool BOOL_HOSPITAL { get; set; }
        public bool BOOL_LOJA { get; set; }
        public string TXT_FLO_ID { get; set; }
        public bool BOOL_MATRIZ { get; set; }
    
        public virtual ICollection<acc_com_hedge> acc_com_hedge { get; set; }
        public virtual ICollection<bebida_padrao> bebida_padrao { get; set; }
        public virtual ICollection<certificacao> certificacao { get; set; }
        public virtual ICollection<cfop> cfop { get; set; }
        public virtual ICollection<comercial_ativo> comercial_ativo { get; set; }
        public virtual ICollection<conciliacoes> conciliacoes { get; set; }
        public virtual ICollection<configuracao_nota_filial> configuracao_nota_filial { get; set; }
        public virtual ICollection<configuracao_nota_filial> configuracao_nota_filial1 { get; set; }
        public virtual ICollection<contas_a_pagar_e_receber> contas_a_pagar_e_receber { get; set; }
        public virtual ICollection<convenio_medico> convenio_medico { get; set; }
        public virtual ICollection<convenio_plano_de_saude> convenio_plano_de_saude { get; set; }
        public virtual ICollection<curso> curso { get; set; }
        public virtual ICollection<defeito_cafe> defeito_cafe { get; set; }
        public virtual ICollection<funcionario> funcionario { get; set; }
        public virtual ICollection<grupo_de_imposto> grupo_de_imposto { get; set; }
        public virtual ICollection<grupo_de_servico> grupo_de_servico { get; set; }
        public virtual ICollection<informacao_adicional> informacao_adicional { get; set; }
        public virtual ICollection<produto_linha> produto_linha { get; set; }
        public virtual ICollection<lote_produto> lote_produto { get; set; }
        public virtual ICollection<maquinario> maquinario { get; set; }
        public virtual ICollection<modalidade_entrega> modalidade_entrega { get; set; }
        public virtual ICollection<movimentos_produtos_contabeis> movimentos_produtos_contabeis { get; set; }
        public virtual ICollection<nota_fiscal> nota_fiscal { get; set; }
        public virtual ICollection<ordem_de_producao> ordem_de_producao { get; set; }
        public virtual ICollection<ordem_de_producao_resultado> ordem_de_producao_resultado { get; set; }
        public virtual ICollection<pedido_faturamento> pedido_faturamento { get; set; }
        public virtual ICollection<pilar> pilar { get; set; }
        public virtual ICollection<planejamento_categoria> planejamento_categoria { get; set; }
        public virtual ICollection<planejamento_item> planejamento_item { get; set; }
        public virtual ICollection<plano_de_contas_contabil> plano_de_contas_contabil { get; set; }
        public virtual ICollection<procedimento_tipo> procedimento_tipo { get; set; }
        public virtual ICollection<rfid_chip> rfid_chip { get; set; }
        public virtual ICollection<tabela_icms> tabela_icms { get; set; }
        public virtual ICollection<tipo_cafe_rebeneficiado> tipo_cafe_rebeneficiado { get; set; }
        public virtual ICollection<tipo_de_contato_com_cliente> tipo_de_contato_com_cliente { get; set; }
        public virtual ICollection<tipo_de_permissao_alas_do_armazem> tipo_de_permissao_alas_do_armazem { get; set; }
        public virtual ICollection<tipo_de_procedimento> tipo_de_procedimento { get; set; }
        public virtual ICollection<tipo_lote_rebeneficio_para_gerar> tipo_lote_rebeneficio_para_gerar { get; set; }
        public virtual ICollection<tipo_sacaria> tipo_sacaria { get; set; }
        public virtual ICollection<transferencia_entre_almoxarifado> transferencia_entre_almoxarifado { get; set; }
        public virtual ICollection<venda_prestacao_servico> venda_prestacao_servico { get; set; }
    }
}
