//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class estrutura_do_produto
    {
        public int INT_ID { get; set; }
        public int INT_ID_PRODUTO_FINAL { get; set; }
        public int INT_ID_PRODUTO_QUE_SERA_UTILIZADO { get; set; }
        public int INT_ID_FUNCIONARIO { get; set; }
        public decimal DECIMAL_QUANTIDADE_QUE_SERA_UTILIZADO_PARA_GERAR_UM_PRODUTO { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual funcionario funcionario { get; set; }
        public virtual produtos_contabeis produtos_contabeis { get; set; }
        public virtual produtos_contabeis produtos_contabeis1 { get; set; }
    }
}
