//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class fluxo_de_caixa
    {
        public fluxo_de_caixa()
        {
            this.pagamento_recebimento_fluxo_de_caixa = new HashSet<pagamento_recebimento_fluxo_de_caixa>();
        }
    
        public int INT_ID { get; set; }
        public Nullable<int> INT_ID_CONTAS_A_PAGAR { get; set; }
        public decimal DECIMAL_VALOR { get; set; }
        public System.DateTime DATE_VENCIMENTO { get; set; }
        public bool BOOL_REAL_DOLAR { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public Nullable<int> INT_ID_ACC { get; set; }
        public bool BOOL_CONTAS_A_PAGAR { get; set; }
        public Nullable<int> INT_ID_CONTRATO { get; set; }
        public Nullable<int> INT_ID_NOTA_FISCAL { get; set; }
        public Nullable<int> INT_ID_FORMA_DE_PAGAMENTO { get; set; }
        public Nullable<int> INT_ID_PARCELAMENTO { get; set; }
        public bool BOOL_CONTAS_DUVIDOSAS { get; set; }
    
        public virtual acc_com_hedge acc_com_hedge { get; set; }
        public virtual contas_a_pagar_e_receber contas_a_pagar_e_receber { get; set; }
        public virtual contrato contrato { get; set; }
        public virtual forma_de_pagamento forma_de_pagamento { get; set; }
        public virtual nota_fiscal nota_fiscal { get; set; }
        public virtual tipo_de_pagamento tipo_de_pagamento { get; set; }
        public virtual ICollection<pagamento_recebimento_fluxo_de_caixa> pagamento_recebimento_fluxo_de_caixa { get; set; }
    }
}
