//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class formulario_aplicar
    {
        public formulario_aplicar()
        {
            this.formulario_aplicar_agendamento_talhao_propriedade = new HashSet<formulario_aplicar_agendamento_talhao_propriedade>();
            this.formulario_aplicar_produtos_utilizados_na_lavoura = new HashSet<formulario_aplicar_produtos_utilizados_na_lavoura>();
            this.formulario_exercicio_rastreabilidade_balanco_massa = new HashSet<formulario_exercicio_rastreabilidade_balanco_massa>();
            this.formulario_aplicar1 = new HashSet<formulario_aplicar>();
            this.formulario_respostas = new HashSet<formulario_respostas>();
        }
    
        public int INT_ID { get; set; }
        public Nullable<int> INT_ID_COOPERADO { get; set; }
        public int INT_ID_APLICOU { get; set; }
        public System.DateTime DATE_INI { get; set; }
        public Nullable<System.DateTime> DATE_FIM { get; set; }
        public string TXT_OBS { get; set; }
        public string TXT_CAMINHO_ANEXAR_DOC_REDUCAO_TEMPO_TRANSICAO { get; set; }
        public bool BOOL_COLETA_AMOSTRA { get; set; }
        public bool BOOL_SOLICITACAO_REDUCAO_TEMPO_TRANSICAO { get; set; }
        public decimal DECIMAL_TEMPO_CONVERSAO { get; set; }
        public bool BOOL_CADERNO_CAMPO_ATUALIZADO { get; set; }
        public int INT_ID_CADASTRO { get; set; }
        public System.DateTime DATE_CADASTRO { get; set; }
        public Nullable<int> INT_ID_ALTERACACAO { get; set; }
        public Nullable<System.DateTime> DATE_ALTERACAO { get; set; }
        public Nullable<int> INT_ID_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DATE_EXCLUSAO { get; set; }
        public Nullable<int> INT_ID_AGENDAMENTO_FORMULARIO_SER_APLICADO { get; set; }
        public int INT_ID_FORMULARIO { get; set; }
        public string TXT_OBS_REDUCAO_TEMPO_TRANSICAO { get; set; }
        public Nullable<bool> BOOL_CONSEGUIU_FAZER_RASTREABILIDADE { get; set; }
        public string TXT_DESCRICAO_RASTREABILIDADE { get; set; }
        public string TXT_DESCRICAO_BALANCO_MASSA { get; set; }
        public string CHAR_VERSAO { get; set; }
        public Nullable<int> INT_ID_FORMULARIO_APLICAR_RASTREAR { get; set; }
        public bool BOOL_AVALIACAO_PELO_CLIENTE { get; set; }
        public string CHAR_RESULTADO { get; set; }
        public Nullable<bool> BOOL_MAPA_CONFORME { get; set; }
        public string TXT_OBS_MAPA { get; set; }
        public string TXT_OBS_CADASTRO { get; set; }
        public bool BOOL_CERTIFICADO_POR_OUTRA_CERTIFICADORA { get; set; }
        public string TXT_DESCRICAO_CERTIFICADORA { get; set; }
        public Nullable<bool> BOOL_PLANO_CONVERSAO_C_NC_NA { get; set; }
        public string TXT_OBS_PLANO_CONVERSAO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public Nullable<bool> BOOL_AROVADO_ANALISTA_SCI { get; set; }
        public string TXT_OBS_ANALISTA_SCI { get; set; }
        public Nullable<bool> BOOL_APROVADO_GESTOR { get; set; }
        public string TXT_OBS_GESTOR { get; set; }
        public string TXT_CONTATACAO { get; set; }
        public string TXT_RECOMENDACAO { get; set; }
        public string TXT_OBS_AVALIACAO_CLIENTE { get; set; }
        public string TXT_ASSINATURA { get; set; }
        public string TXT_MOTIVO_DE_NAO_COLETAR_ASSINATURA { get; set; }
    
        public virtual agendamento_formulario_ser_aplicado agendamento_formulario_ser_aplicado { get; set; }
        public virtual cooperado cooperado { get; set; }
        public virtual formulario formulario { get; set; }
        public virtual ICollection<formulario_aplicar_agendamento_talhao_propriedade> formulario_aplicar_agendamento_talhao_propriedade { get; set; }
        public virtual ICollection<formulario_aplicar_produtos_utilizados_na_lavoura> formulario_aplicar_produtos_utilizados_na_lavoura { get; set; }
        public virtual ICollection<formulario_exercicio_rastreabilidade_balanco_massa> formulario_exercicio_rastreabilidade_balanco_massa { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        public virtual funcionario funcionario2 { get; set; }
        public virtual funcionario funcionario3 { get; set; }
        public virtual ICollection<formulario_aplicar> formulario_aplicar1 { get; set; }
        public virtual formulario_aplicar formulario_aplicar2 { get; set; }
        public virtual ICollection<formulario_respostas> formulario_respostas { get; set; }
    }
}
