//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class formulario_aplicar_agendamento_talhao_propriedade
    {
        public int INT_ID { get; set; }
        public int INT_ID_FORM_APLICAR { get; set; }
        public int INT_ID_AGENDAMENTO_TALHAO_PROPRIEDADE { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual agendamento_talhao_propriedade agendamento_talhao_propriedade { get; set; }
        public virtual formulario_aplicar formulario_aplicar { get; set; }
    }
}
