//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class formulario_aplicar_produtos_utilizados_na_lavoura
    {
        public formulario_aplicar_produtos_utilizados_na_lavoura()
        {
            this.aplicador_de_produtos_na_lavoura = new HashSet<aplicador_de_produtos_na_lavoura>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_FORMULARIO_APLICAR { get; set; }
        public int INT_ID_FORMULARIO_ITEM_SELECAO { get; set; }
        public System.DateTime DATE_APLICOU { get; set; }
        public Nullable<int> INT_ID_TALHAO { get; set; }
        public string TXT_OBS { get; set; }
        public bool BOOL_APLICADO_PELO_PROPRIO_PRODUTOR { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public int INT_ID_CADASTROU { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public Nullable<int> INT_ID_ALTEROU { get; set; }
        public Nullable<System.DateTime> DATE_ALTEROU { get; set; }
        public Nullable<int> INT_ID_EXCLUIU { get; set; }
        public Nullable<System.DateTime> DATE_EXCLUIU { get; set; }
    
        public virtual ICollection<aplicador_de_produtos_na_lavoura> aplicador_de_produtos_na_lavoura { get; set; }
        public virtual formulario_aplicar formulario_aplicar { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        public virtual funcionario funcionario2 { get; set; }
        public virtual formulario_item_selecao formulario_item_selecao { get; set; }
        public virtual talhao talhao { get; set; }
    }
}
