//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class forma_de_pagamento
    {
        public forma_de_pagamento()
        {
            this.contrato = new HashSet<contrato>();
            this.cotacao_compra = new HashSet<cotacao_compra>();
            this.emprestimos = new HashSet<emprestimos>();
            this.fluxo_de_caixa = new HashSet<fluxo_de_caixa>();
            this.intervalo_da_forma_pagamento = new HashSet<intervalo_da_forma_pagamento>();
            this.pronaf = new HashSet<pronaf>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_FORMA_DE_PAGAMENTO { get; set; }
        public int INT_NUM_PAR { get; set; }
        public bool BOOL_FLAG { get; set; }
        public string TXT_DESCRICAO_INGLES { get; set; }
    
        public virtual ICollection<contrato> contrato { get; set; }
        public virtual ICollection<cotacao_compra> cotacao_compra { get; set; }
        public virtual ICollection<emprestimos> emprestimos { get; set; }
        public virtual ICollection<fluxo_de_caixa> fluxo_de_caixa { get; set; }
        public virtual ICollection<intervalo_da_forma_pagamento> intervalo_da_forma_pagamento { get; set; }
        public virtual ICollection<pronaf> pronaf { get; set; }
    }
}
