//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class funcionario
    {
        public funcionario()
        {
            this.acc_com_hedge = new HashSet<acc_com_hedge>();
            this.agendamento_carga_descarga = new HashSet<agendamento_carga_descarga>();
            this.agendamento_certificacao = new HashSet<agendamento_certificacao>();
            this.agendamento_certificacao1 = new HashSet<agendamento_certificacao>();
            this.agendamento_certificacao2 = new HashSet<agendamento_certificacao>();
            this.agendamento_certificacao3 = new HashSet<agendamento_certificacao>();
            this.agendamento_certificacao4 = new HashSet<agendamento_certificacao>();
            this.agendamento_cooperado = new HashSet<agendamento_cooperado>();
            this.alas_do_armazem_lotes = new HashSet<alas_do_armazem_lotes>();
            this.alas_do_armazem_lotes1 = new HashSet<alas_do_armazem_lotes>();
            this.amostra_da_roca = new HashSet<amostra_da_roca>();
            this.amostra_solo_foliar = new HashSet<amostra_solo_foliar>();
            this.amostra_solo_foliar1 = new HashSet<amostra_solo_foliar>();
            this.amostra_solo_foliar2 = new HashSet<amostra_solo_foliar>();
            this.amostra_solo_foliar3 = new HashSet<amostra_solo_foliar>();
            this.amostra_solo_foliar4 = new HashSet<amostra_solo_foliar>();
            this.amostra_solo_foliar5 = new HashSet<amostra_solo_foliar>();
            this.autorizacao_generica = new HashSet<autorizacao_generica>();
            this.autorizacao_generica1 = new HashSet<autorizacao_generica>();
            this.autorizacao_generica2 = new HashSet<autorizacao_generica>();
            this.autorizacao_generica3 = new HashSet<autorizacao_generica>();
            this.cadastro_entrada = new HashSet<cadastro_entrada>();
            this.comercial_ativo = new HashSet<comercial_ativo>();
            this.complementacoes_lote = new HashSet<complementacoes_lote>();
            this.composicao_amostra_envio = new HashSet<composicao_amostra_envio>();
            this.contas_a_pagar_e_receber = new HashSet<contas_a_pagar_e_receber>();
            this.convenio_medico_guia = new HashSet<convenio_medico_guia>();
            this.convenio_medico_guia1 = new HashSet<convenio_medico_guia>();
            this.convenio_medico_guia2 = new HashSet<convenio_medico_guia>();
            this.convenio_titular = new HashSet<convenio_titular>();
            this.cooperado = new HashSet<cooperado>();
            this.cooperado_que_fazem_parte_do_mercado_futuro = new HashSet<cooperado_que_fazem_parte_do_mercado_futuro>();
            this.cooperado_que_fazem_parte_do_mercado_futuro1 = new HashSet<cooperado_que_fazem_parte_do_mercado_futuro>();
            this.cooperado_que_fazem_parte_do_mercado_futuro2 = new HashSet<cooperado_que_fazem_parte_do_mercado_futuro>();
            this.cotacao_compra = new HashSet<cotacao_compra>();
            this.cotacao_compra1 = new HashSet<cotacao_compra>();
            this.cotacao_compra2 = new HashSet<cotacao_compra>();
            this.cotacao_compra_item = new HashSet<cotacao_compra_item>();
            this.cotacao_compra_item1 = new HashSet<cotacao_compra_item>();
            this.cotacao_compra_item2 = new HashSet<cotacao_compra_item>();
            this.cotacao_item = new HashSet<cotacao_item>();
            this.cotacao_item1 = new HashSet<cotacao_item>();
            this.cotacao_item2 = new HashSet<cotacao_item>();
            this.criterios = new HashSet<criterios>();
            this.criterios1 = new HashSet<criterios>();
            this.criterios2 = new HashSet<criterios>();
            this.curso_realizados = new HashSet<curso_realizados>();
            this.curso_realizados1 = new HashSet<curso_realizados>();
            this.curso_realizados2 = new HashSet<curso_realizados>();
            this.cursos_cooperados = new HashSet<cursos_cooperados>();
            this.cursos_cooperados1 = new HashSet<cursos_cooperados>();
            this.dependentes_plano_de_saude = new HashSet<dependentes_plano_de_saude>();
            this.dependentes_plano_de_saude1 = new HashSet<dependentes_plano_de_saude>();
            this.descontos_acrescimos_pg_cafe = new HashSet<descontos_acrescimos_pg_cafe>();
            this.devolucao_de_compra = new HashSet<devolucao_de_compra>();
            this.devolucao_de_compra1 = new HashSet<devolucao_de_compra>();
            this.devolucao_de_compra2 = new HashSet<devolucao_de_compra>();
            this.emprestimos = new HashSet<emprestimos>();
            this.estrutura_do_produto = new HashSet<estrutura_do_produto>();
            this.fechamento_mercado_futuro = new HashSet<fechamento_mercado_futuro>();
            this.fechamento_mercado_futuro1 = new HashSet<fechamento_mercado_futuro>();
            this.fechamento_mercado_futuro2 = new HashSet<fechamento_mercado_futuro>();
            this.form_resposta_nc_criterio = new HashSet<form_resposta_nc_criterio>();
            this.form_resposta_nc_criterio1 = new HashSet<form_resposta_nc_criterio>();
            this.form_resposta_nc_criterio2 = new HashSet<form_resposta_nc_criterio>();
            this.formulario = new HashSet<formulario>();
            this.formulario1 = new HashSet<formulario>();
            this.formulario2 = new HashSet<formulario>();
            this.formulario_aplicar = new HashSet<formulario_aplicar>();
            this.formulario_aplicar1 = new HashSet<formulario_aplicar>();
            this.formulario_aplicar2 = new HashSet<formulario_aplicar>();
            this.formulario_aplicar3 = new HashSet<formulario_aplicar>();
            this.formulario_aplicar_produtos_utilizados_na_lavoura = new HashSet<formulario_aplicar_produtos_utilizados_na_lavoura>();
            this.formulario_aplicar_produtos_utilizados_na_lavoura1 = new HashSet<formulario_aplicar_produtos_utilizados_na_lavoura>();
            this.formulario_aplicar_produtos_utilizados_na_lavoura2 = new HashSet<formulario_aplicar_produtos_utilizados_na_lavoura>();
            this.formulario_checklist = new HashSet<formulario_checklist>();
            this.formulario_checklist1 = new HashSet<formulario_checklist>();
            this.formulario_checklist2 = new HashSet<formulario_checklist>();
            this.formulario_exercicio_rastreabilidade_balanco_massa = new HashSet<formulario_exercicio_rastreabilidade_balanco_massa>();
            this.formulario_exercicio_rastreabilidade_balanco_massa1 = new HashSet<formulario_exercicio_rastreabilidade_balanco_massa>();
            this.formulario_exercicio_rastreabilidade_balanco_massa2 = new HashSet<formulario_exercicio_rastreabilidade_balanco_massa>();
            this.formulario_item = new HashSet<formulario_item>();
            this.formulario_item1 = new HashSet<formulario_item>();
            this.formulario_item2 = new HashSet<formulario_item>();
            this.formulario_resposta_documento_comprobatorio = new HashSet<formulario_resposta_documento_comprobatorio>();
            this.formulario_resposta_documento_comprobatorio1 = new HashSet<formulario_resposta_documento_comprobatorio>();
            this.formulario_resposta_documento_comprobatorio2 = new HashSet<formulario_resposta_documento_comprobatorio>();
            this.formulario_resposta_seletiva = new HashSet<formulario_resposta_seletiva>();
            this.formulario_resposta_seletiva1 = new HashSet<formulario_resposta_seletiva>();
            this.formulario_resposta_seletiva2 = new HashSet<formulario_resposta_seletiva>();
            this.formulario_respostas = new HashSet<formulario_respostas>();
            this.formulario_respostas1 = new HashSet<formulario_respostas>();
            this.formulario_respostas2 = new HashSet<formulario_respostas>();
            this.formulario_sub_item = new HashSet<formulario_sub_item>();
            this.formulario_sub_item1 = new HashSet<formulario_sub_item>();
            this.formulario_sub_item2 = new HashSet<formulario_sub_item>();
            this.formulario_subitem_ref_criterio = new HashSet<formulario_subitem_ref_criterio>();
            this.formulario_subitem_ref_criterio1 = new HashSet<formulario_subitem_ref_criterio>();
            this.formulario_subitem_ref_criterio2 = new HashSet<formulario_subitem_ref_criterio>();
            this.hedge = new HashSet<hedge>();
            this.log_erro_do_sistema = new HashSet<log_erro_do_sistema>();
            this.rolagem = new HashSet<rolagem>();
            this.lancamento_extras_codigos_contabeis = new HashSet<lancamento_extras_codigos_contabeis>();
            this.instrucao_preparo = new HashSet<instrucao_preparo>();
            this.log_usuarios = new HashSet<log_usuarios>();
            this.instrucao_preparo1 = new HashSet<instrucao_preparo>();
            this.instrucao_preparo2 = new HashSet<instrucao_preparo>();
            this.integracao_contabil = new HashSet<integracao_contabil>();
            this.integracao_contabil1 = new HashSet<integracao_contabil>();
            this.liquidacao_contrato_de_cambio = new HashSet<liquidacao_contrato_de_cambio>();
            this.lote_para_analise_solo_foliar = new HashSet<lote_para_analise_solo_foliar>();
            this.lote_para_analise_solo_foliar1 = new HashSet<lote_para_analise_solo_foliar>();
            this.lote_para_analise_solo_foliar2 = new HashSet<lote_para_analise_solo_foliar>();
            this.lote_para_analise_solo_foliar3 = new HashSet<lote_para_analise_solo_foliar>();
            this.lote_produto = new HashSet<lote_produto>();
            this.movimentos_produtos_contabeis = new HashSet<movimentos_produtos_contabeis>();
            this.movimento_bancario = new HashSet<movimento_bancario>();
            this.movimento_bancario1 = new HashSet<movimento_bancario>();
            this.norma_talhao = new HashSet<norma_talhao>();
            this.norma_talhao1 = new HashSet<norma_talhao>();
            this.nota_fiscal = new HashSet<nota_fiscal>();
            this.nota_fiscal1 = new HashSet<nota_fiscal>();
            this.notas_canceladas = new HashSet<notas_canceladas>();
            this.ordem_de_producao = new HashSet<ordem_de_producao>();
            this.ordem_de_producao1 = new HashSet<ordem_de_producao>();
            this.ordem_de_producao2 = new HashSet<ordem_de_producao>();
            this.ordem_de_producao3 = new HashSet<ordem_de_producao>();
            this.ordem_de_producao4 = new HashSet<ordem_de_producao>();
            this.ordem_de_producao5 = new HashSet<ordem_de_producao>();
            this.ordem_de_producao6 = new HashSet<ordem_de_producao>();
            this.ordem_de_producao7 = new HashSet<ordem_de_producao>();
            this.ordem_de_producao8 = new HashSet<ordem_de_producao>();
            this.ordem_de_producao_produtos_utilizados = new HashSet<ordem_de_producao_produtos_utilizados>();
            this.ordem_de_producao_produtos = new HashSet<ordem_de_producao_produtos>();
            this.ordem_de_producao_resultado = new HashSet<ordem_de_producao_resultado>();
            this.ordem_de_producao_tempo = new HashSet<ordem_de_producao_tempo>();
            this.ordem_de_producao_tempo1 = new HashSet<ordem_de_producao_tempo>();
            this.ordem_de_producao_tempo2 = new HashSet<ordem_de_producao_tempo>();
            this.ordem_de_producao_tempo3 = new HashSet<ordem_de_producao_tempo>();
            this.ordem_de_producao_tempo4 = new HashSet<ordem_de_producao_tempo>();
            this.ordem_de_producao_tempo5 = new HashSet<ordem_de_producao_tempo>();
            this.ordem_de_producao_tempo6 = new HashSet<ordem_de_producao_tempo>();
            this.ordem_de_producao_tempo7 = new HashSet<ordem_de_producao_tempo>();
            this.pedido_faturamento = new HashSet<pedido_faturamento>();
            this.pedido_faturamento1 = new HashSet<pedido_faturamento>();
            this.pedido_faturamento_produto = new HashSet<pedido_faturamento_produto>();
            this.pagamento_emprestimo = new HashSet<pagamento_emprestimo>();
            this.planejamento_auto_avaliacao_impacto = new HashSet<planejamento_auto_avaliacao_impacto>();
            this.planejamento_auto_avaliacao_impacto1 = new HashSet<planejamento_auto_avaliacao_impacto>();
            this.planejamento_responsavel = new HashSet<planejamento_responsavel>();
            this.plano_conversao = new HashSet<plano_conversao>();
            this.plano_conversao1 = new HashSet<plano_conversao>();
            this.plano_conversao2 = new HashSet<plano_conversao>();
            this.procedimento = new HashSet<procedimento>();
            this.pronaf = new HashSet<pronaf>();
            this.pronaf1 = new HashSet<pronaf>();
            this.pronaf2 = new HashSet<pronaf>();
            this.recibo_cancelado = new HashSet<recibo_cancelado>();
            this.recibo = new HashSet<recibo>();
            this.relacao_de_notas_desc_acrescimo = new HashSet<relacao_de_notas_desc_acrescimo>();
            this.remocao_de_lotes = new HashSet<remocao_de_lotes>();
            this.requisicao_compra = new HashSet<requisicao_compra>();
            this.requisicao_compra1 = new HashSet<requisicao_compra>();
            this.requisicao_compra2 = new HashSet<requisicao_compra>();
            this.origem_do_produto = new HashSet<origem_do_produto>();
            this.resultado_rebeneficio = new HashSet<resultado_rebeneficio>();
            this.resultado_rebeneficio1 = new HashSet<resultado_rebeneficio>();
            this.resultado_rebeneficio2 = new HashSet<resultado_rebeneficio>();
            this.solicitacao_de_amostra = new HashSet<solicitacao_de_amostra>();
            this.solicitacao_de_amostra1 = new HashSet<solicitacao_de_amostra>();
            this.solicitacao_de_amostra_lote = new HashSet<solicitacao_de_amostra_lote>();
            this.solicitacao_de_amostra_lote1 = new HashSet<solicitacao_de_amostra_lote>();
            this.solicitacao_de_retirada = new HashSet<solicitacao_de_retirada>();
            this.solicitacao_de_retirada1 = new HashSet<solicitacao_de_retirada>();
            this.talhao_ultima_aplicao_produto_proibido = new HashSet<talhao_ultima_aplicao_produto_proibido>();
            this.talhao_ultima_aplicao_produto_proibido1 = new HashSet<talhao_ultima_aplicao_produto_proibido>();
            this.talhao_ultima_aplicao_produto_proibido2 = new HashSet<talhao_ultima_aplicao_produto_proibido>();
            this.talhao_variedade = new HashSet<talhao_variedade>();
            this.talhao_variedade1 = new HashSet<talhao_variedade>();
            this.talhao_variedade2 = new HashSet<talhao_variedade>();
            this.tipo_de_permissao_alas_do_armazem_normas = new HashSet<tipo_de_permissao_alas_do_armazem_normas>();
            this.transferencia_entre_almoxarifado = new HashSet<transferencia_entre_almoxarifado>();
            this.transferencia_entre_almoxarifado1 = new HashSet<transferencia_entre_almoxarifado>();
            this.transferencia_entre_almoxarifado2 = new HashSet<transferencia_entre_almoxarifado>();
            this.solicitacao_de_unificacao_divisao_de_talhoes = new HashSet<solicitacao_de_unificacao_divisao_de_talhoes>();
            this.solicitacao_de_unificacao_divisao_de_talhoes1 = new HashSet<solicitacao_de_unificacao_divisao_de_talhoes>();
            this.solicitacao_de_unificacao_divisao_de_talhoes2 = new HashSet<solicitacao_de_unificacao_divisao_de_talhoes>();
            this.venda_prestacao_servico = new HashSet<venda_prestacao_servico>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_NOME { get; set; }
        public string TXT_CPF { get; set; }
        public string TXT_RG { get; set; }
        public string TXT_TITULO_ELEITOR { get; set; }
        public string TXT_CARTEIRA_TRABALHO { get; set; }
        public string TXT_TELEFONE { get; set; }
        public string TXT_EMAIL { get; set; }
        public bool BOOL_STATUS { get; set; }
        public string TXT_RUA { get; set; }
        public Nullable<int> INT_NUM { get; set; }
        public string TXT_BAIRRO { get; set; }
        public System.DateTime DATE_ADIMISSAO { get; set; }
        public Nullable<System.DateTime> DATE_DEMISSAO { get; set; }
        public string TXT_SENHA { get; set; }
        public bool BOOL_ESTOQUE { get; set; }
        public bool BOOL_CLASSIFICACAO { get; set; }
        public bool BOOL_CERTIFICACAO { get; set; }
        public bool BOOL_COMERCIAL { get; set; }
        public bool BOOL_GERENTE { get; set; }
        public bool BOOL_ADM { get; set; }
        public bool BOOL_SEXO { get; set; }
        public System.DateTime DATE_NASCIMENTO { get; set; }
        public int INT_ID_EMPRESA { get; set; }
        public string TXT_PERMISSAO { get; set; }
    
        public virtual ICollection<acc_com_hedge> acc_com_hedge { get; set; }
        public virtual ICollection<agendamento_carga_descarga> agendamento_carga_descarga { get; set; }
        public virtual ICollection<agendamento_certificacao> agendamento_certificacao { get; set; }
        public virtual ICollection<agendamento_certificacao> agendamento_certificacao1 { get; set; }
        public virtual ICollection<agendamento_certificacao> agendamento_certificacao2 { get; set; }
        public virtual ICollection<agendamento_certificacao> agendamento_certificacao3 { get; set; }
        public virtual ICollection<agendamento_certificacao> agendamento_certificacao4 { get; set; }
        public virtual ICollection<agendamento_cooperado> agendamento_cooperado { get; set; }
        public virtual ICollection<alas_do_armazem_lotes> alas_do_armazem_lotes { get; set; }
        public virtual ICollection<alas_do_armazem_lotes> alas_do_armazem_lotes1 { get; set; }
        public virtual ICollection<amostra_da_roca> amostra_da_roca { get; set; }
        public virtual ICollection<amostra_solo_foliar> amostra_solo_foliar { get; set; }
        public virtual ICollection<amostra_solo_foliar> amostra_solo_foliar1 { get; set; }
        public virtual ICollection<amostra_solo_foliar> amostra_solo_foliar2 { get; set; }
        public virtual ICollection<amostra_solo_foliar> amostra_solo_foliar3 { get; set; }
        public virtual ICollection<amostra_solo_foliar> amostra_solo_foliar4 { get; set; }
        public virtual ICollection<amostra_solo_foliar> amostra_solo_foliar5 { get; set; }
        public virtual ICollection<autorizacao_generica> autorizacao_generica { get; set; }
        public virtual ICollection<autorizacao_generica> autorizacao_generica1 { get; set; }
        public virtual ICollection<autorizacao_generica> autorizacao_generica2 { get; set; }
        public virtual ICollection<autorizacao_generica> autorizacao_generica3 { get; set; }
        public virtual ICollection<cadastro_entrada> cadastro_entrada { get; set; }
        public virtual ICollection<comercial_ativo> comercial_ativo { get; set; }
        public virtual ICollection<complementacoes_lote> complementacoes_lote { get; set; }
        public virtual ICollection<composicao_amostra_envio> composicao_amostra_envio { get; set; }
        public virtual ICollection<contas_a_pagar_e_receber> contas_a_pagar_e_receber { get; set; }
        public virtual ICollection<convenio_medico_guia> convenio_medico_guia { get; set; }
        public virtual ICollection<convenio_medico_guia> convenio_medico_guia1 { get; set; }
        public virtual ICollection<convenio_medico_guia> convenio_medico_guia2 { get; set; }
        public virtual ICollection<convenio_titular> convenio_titular { get; set; }
        public virtual ICollection<cooperado> cooperado { get; set; }
        public virtual ICollection<cooperado_que_fazem_parte_do_mercado_futuro> cooperado_que_fazem_parte_do_mercado_futuro { get; set; }
        public virtual ICollection<cooperado_que_fazem_parte_do_mercado_futuro> cooperado_que_fazem_parte_do_mercado_futuro1 { get; set; }
        public virtual ICollection<cooperado_que_fazem_parte_do_mercado_futuro> cooperado_que_fazem_parte_do_mercado_futuro2 { get; set; }
        public virtual ICollection<cotacao_compra> cotacao_compra { get; set; }
        public virtual ICollection<cotacao_compra> cotacao_compra1 { get; set; }
        public virtual ICollection<cotacao_compra> cotacao_compra2 { get; set; }
        public virtual ICollection<cotacao_compra_item> cotacao_compra_item { get; set; }
        public virtual ICollection<cotacao_compra_item> cotacao_compra_item1 { get; set; }
        public virtual ICollection<cotacao_compra_item> cotacao_compra_item2 { get; set; }
        public virtual ICollection<cotacao_item> cotacao_item { get; set; }
        public virtual ICollection<cotacao_item> cotacao_item1 { get; set; }
        public virtual ICollection<cotacao_item> cotacao_item2 { get; set; }
        public virtual ICollection<criterios> criterios { get; set; }
        public virtual ICollection<criterios> criterios1 { get; set; }
        public virtual ICollection<criterios> criterios2 { get; set; }
        public virtual ICollection<curso_realizados> curso_realizados { get; set; }
        public virtual ICollection<curso_realizados> curso_realizados1 { get; set; }
        public virtual ICollection<curso_realizados> curso_realizados2 { get; set; }
        public virtual ICollection<cursos_cooperados> cursos_cooperados { get; set; }
        public virtual ICollection<cursos_cooperados> cursos_cooperados1 { get; set; }
        public virtual ICollection<dependentes_plano_de_saude> dependentes_plano_de_saude { get; set; }
        public virtual ICollection<dependentes_plano_de_saude> dependentes_plano_de_saude1 { get; set; }
        public virtual ICollection<descontos_acrescimos_pg_cafe> descontos_acrescimos_pg_cafe { get; set; }
        public virtual ICollection<devolucao_de_compra> devolucao_de_compra { get; set; }
        public virtual ICollection<devolucao_de_compra> devolucao_de_compra1 { get; set; }
        public virtual ICollection<devolucao_de_compra> devolucao_de_compra2 { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual ICollection<emprestimos> emprestimos { get; set; }
        public virtual ICollection<estrutura_do_produto> estrutura_do_produto { get; set; }
        public virtual ICollection<fechamento_mercado_futuro> fechamento_mercado_futuro { get; set; }
        public virtual ICollection<fechamento_mercado_futuro> fechamento_mercado_futuro1 { get; set; }
        public virtual ICollection<fechamento_mercado_futuro> fechamento_mercado_futuro2 { get; set; }
        public virtual ICollection<form_resposta_nc_criterio> form_resposta_nc_criterio { get; set; }
        public virtual ICollection<form_resposta_nc_criterio> form_resposta_nc_criterio1 { get; set; }
        public virtual ICollection<form_resposta_nc_criterio> form_resposta_nc_criterio2 { get; set; }
        public virtual ICollection<formulario> formulario { get; set; }
        public virtual ICollection<formulario> formulario1 { get; set; }
        public virtual ICollection<formulario> formulario2 { get; set; }
        public virtual ICollection<formulario_aplicar> formulario_aplicar { get; set; }
        public virtual ICollection<formulario_aplicar> formulario_aplicar1 { get; set; }
        public virtual ICollection<formulario_aplicar> formulario_aplicar2 { get; set; }
        public virtual ICollection<formulario_aplicar> formulario_aplicar3 { get; set; }
        public virtual ICollection<formulario_aplicar_produtos_utilizados_na_lavoura> formulario_aplicar_produtos_utilizados_na_lavoura { get; set; }
        public virtual ICollection<formulario_aplicar_produtos_utilizados_na_lavoura> formulario_aplicar_produtos_utilizados_na_lavoura1 { get; set; }
        public virtual ICollection<formulario_aplicar_produtos_utilizados_na_lavoura> formulario_aplicar_produtos_utilizados_na_lavoura2 { get; set; }
        public virtual ICollection<formulario_checklist> formulario_checklist { get; set; }
        public virtual ICollection<formulario_checklist> formulario_checklist1 { get; set; }
        public virtual ICollection<formulario_checklist> formulario_checklist2 { get; set; }
        public virtual ICollection<formulario_exercicio_rastreabilidade_balanco_massa> formulario_exercicio_rastreabilidade_balanco_massa { get; set; }
        public virtual ICollection<formulario_exercicio_rastreabilidade_balanco_massa> formulario_exercicio_rastreabilidade_balanco_massa1 { get; set; }
        public virtual ICollection<formulario_exercicio_rastreabilidade_balanco_massa> formulario_exercicio_rastreabilidade_balanco_massa2 { get; set; }
        public virtual ICollection<formulario_item> formulario_item { get; set; }
        public virtual ICollection<formulario_item> formulario_item1 { get; set; }
        public virtual ICollection<formulario_item> formulario_item2 { get; set; }
        public virtual ICollection<formulario_resposta_documento_comprobatorio> formulario_resposta_documento_comprobatorio { get; set; }
        public virtual ICollection<formulario_resposta_documento_comprobatorio> formulario_resposta_documento_comprobatorio1 { get; set; }
        public virtual ICollection<formulario_resposta_documento_comprobatorio> formulario_resposta_documento_comprobatorio2 { get; set; }
        public virtual ICollection<formulario_resposta_seletiva> formulario_resposta_seletiva { get; set; }
        public virtual ICollection<formulario_resposta_seletiva> formulario_resposta_seletiva1 { get; set; }
        public virtual ICollection<formulario_resposta_seletiva> formulario_resposta_seletiva2 { get; set; }
        public virtual ICollection<formulario_respostas> formulario_respostas { get; set; }
        public virtual ICollection<formulario_respostas> formulario_respostas1 { get; set; }
        public virtual ICollection<formulario_respostas> formulario_respostas2 { get; set; }
        public virtual ICollection<formulario_sub_item> formulario_sub_item { get; set; }
        public virtual ICollection<formulario_sub_item> formulario_sub_item1 { get; set; }
        public virtual ICollection<formulario_sub_item> formulario_sub_item2 { get; set; }
        public virtual ICollection<formulario_subitem_ref_criterio> formulario_subitem_ref_criterio { get; set; }
        public virtual ICollection<formulario_subitem_ref_criterio> formulario_subitem_ref_criterio1 { get; set; }
        public virtual ICollection<formulario_subitem_ref_criterio> formulario_subitem_ref_criterio2 { get; set; }
        public virtual ICollection<hedge> hedge { get; set; }
        public virtual ICollection<log_erro_do_sistema> log_erro_do_sistema { get; set; }
        public virtual ICollection<rolagem> rolagem { get; set; }
        public virtual ICollection<lancamento_extras_codigos_contabeis> lancamento_extras_codigos_contabeis { get; set; }
        public virtual ICollection<instrucao_preparo> instrucao_preparo { get; set; }
        public virtual ICollection<log_usuarios> log_usuarios { get; set; }
        public virtual ICollection<instrucao_preparo> instrucao_preparo1 { get; set; }
        public virtual ICollection<instrucao_preparo> instrucao_preparo2 { get; set; }
        public virtual ICollection<integracao_contabil> integracao_contabil { get; set; }
        public virtual ICollection<integracao_contabil> integracao_contabil1 { get; set; }
        public virtual ICollection<liquidacao_contrato_de_cambio> liquidacao_contrato_de_cambio { get; set; }
        public virtual ICollection<lote_para_analise_solo_foliar> lote_para_analise_solo_foliar { get; set; }
        public virtual ICollection<lote_para_analise_solo_foliar> lote_para_analise_solo_foliar1 { get; set; }
        public virtual ICollection<lote_para_analise_solo_foliar> lote_para_analise_solo_foliar2 { get; set; }
        public virtual ICollection<lote_para_analise_solo_foliar> lote_para_analise_solo_foliar3 { get; set; }
        public virtual ICollection<lote_produto> lote_produto { get; set; }
        public virtual ICollection<movimentos_produtos_contabeis> movimentos_produtos_contabeis { get; set; }
        public virtual ICollection<movimento_bancario> movimento_bancario { get; set; }
        public virtual ICollection<movimento_bancario> movimento_bancario1 { get; set; }
        public virtual ICollection<norma_talhao> norma_talhao { get; set; }
        public virtual ICollection<norma_talhao> norma_talhao1 { get; set; }
        public virtual ICollection<nota_fiscal> nota_fiscal { get; set; }
        public virtual ICollection<nota_fiscal> nota_fiscal1 { get; set; }
        public virtual ICollection<notas_canceladas> notas_canceladas { get; set; }
        public virtual ICollection<ordem_de_producao> ordem_de_producao { get; set; }
        public virtual ICollection<ordem_de_producao> ordem_de_producao1 { get; set; }
        public virtual ICollection<ordem_de_producao> ordem_de_producao2 { get; set; }
        public virtual ICollection<ordem_de_producao> ordem_de_producao3 { get; set; }
        public virtual ICollection<ordem_de_producao> ordem_de_producao4 { get; set; }
        public virtual ICollection<ordem_de_producao> ordem_de_producao5 { get; set; }
        public virtual ICollection<ordem_de_producao> ordem_de_producao6 { get; set; }
        public virtual ICollection<ordem_de_producao> ordem_de_producao7 { get; set; }
        public virtual ICollection<ordem_de_producao> ordem_de_producao8 { get; set; }
        public virtual ICollection<ordem_de_producao_produtos_utilizados> ordem_de_producao_produtos_utilizados { get; set; }
        public virtual ICollection<ordem_de_producao_produtos> ordem_de_producao_produtos { get; set; }
        public virtual ICollection<ordem_de_producao_resultado> ordem_de_producao_resultado { get; set; }
        public virtual ICollection<ordem_de_producao_tempo> ordem_de_producao_tempo { get; set; }
        public virtual ICollection<ordem_de_producao_tempo> ordem_de_producao_tempo1 { get; set; }
        public virtual ICollection<ordem_de_producao_tempo> ordem_de_producao_tempo2 { get; set; }
        public virtual ICollection<ordem_de_producao_tempo> ordem_de_producao_tempo3 { get; set; }
        public virtual ICollection<ordem_de_producao_tempo> ordem_de_producao_tempo4 { get; set; }
        public virtual ICollection<ordem_de_producao_tempo> ordem_de_producao_tempo5 { get; set; }
        public virtual ICollection<ordem_de_producao_tempo> ordem_de_producao_tempo6 { get; set; }
        public virtual ICollection<ordem_de_producao_tempo> ordem_de_producao_tempo7 { get; set; }
        public virtual ICollection<pedido_faturamento> pedido_faturamento { get; set; }
        public virtual ICollection<pedido_faturamento> pedido_faturamento1 { get; set; }
        public virtual ICollection<pedido_faturamento_produto> pedido_faturamento_produto { get; set; }
        public virtual ICollection<pagamento_emprestimo> pagamento_emprestimo { get; set; }
        public virtual ICollection<planejamento_auto_avaliacao_impacto> planejamento_auto_avaliacao_impacto { get; set; }
        public virtual ICollection<planejamento_auto_avaliacao_impacto> planejamento_auto_avaliacao_impacto1 { get; set; }
        public virtual ICollection<planejamento_responsavel> planejamento_responsavel { get; set; }
        public virtual ICollection<plano_conversao> plano_conversao { get; set; }
        public virtual ICollection<plano_conversao> plano_conversao1 { get; set; }
        public virtual ICollection<plano_conversao> plano_conversao2 { get; set; }
        public virtual ICollection<procedimento> procedimento { get; set; }
        public virtual ICollection<pronaf> pronaf { get; set; }
        public virtual ICollection<pronaf> pronaf1 { get; set; }
        public virtual ICollection<pronaf> pronaf2 { get; set; }
        public virtual ICollection<recibo_cancelado> recibo_cancelado { get; set; }
        public virtual ICollection<recibo> recibo { get; set; }
        public virtual ICollection<relacao_de_notas_desc_acrescimo> relacao_de_notas_desc_acrescimo { get; set; }
        public virtual ICollection<remocao_de_lotes> remocao_de_lotes { get; set; }
        public virtual ICollection<requisicao_compra> requisicao_compra { get; set; }
        public virtual ICollection<requisicao_compra> requisicao_compra1 { get; set; }
        public virtual ICollection<requisicao_compra> requisicao_compra2 { get; set; }
        public virtual ICollection<origem_do_produto> origem_do_produto { get; set; }
        public virtual ICollection<resultado_rebeneficio> resultado_rebeneficio { get; set; }
        public virtual ICollection<resultado_rebeneficio> resultado_rebeneficio1 { get; set; }
        public virtual ICollection<resultado_rebeneficio> resultado_rebeneficio2 { get; set; }
        public virtual ICollection<solicitacao_de_amostra> solicitacao_de_amostra { get; set; }
        public virtual ICollection<solicitacao_de_amostra> solicitacao_de_amostra1 { get; set; }
        public virtual ICollection<solicitacao_de_amostra_lote> solicitacao_de_amostra_lote { get; set; }
        public virtual ICollection<solicitacao_de_amostra_lote> solicitacao_de_amostra_lote1 { get; set; }
        public virtual ICollection<solicitacao_de_retirada> solicitacao_de_retirada { get; set; }
        public virtual ICollection<solicitacao_de_retirada> solicitacao_de_retirada1 { get; set; }
        public virtual ICollection<talhao_ultima_aplicao_produto_proibido> talhao_ultima_aplicao_produto_proibido { get; set; }
        public virtual ICollection<talhao_ultima_aplicao_produto_proibido> talhao_ultima_aplicao_produto_proibido1 { get; set; }
        public virtual ICollection<talhao_ultima_aplicao_produto_proibido> talhao_ultima_aplicao_produto_proibido2 { get; set; }
        public virtual ICollection<talhao_variedade> talhao_variedade { get; set; }
        public virtual ICollection<talhao_variedade> talhao_variedade1 { get; set; }
        public virtual ICollection<talhao_variedade> talhao_variedade2 { get; set; }
        public virtual ICollection<tipo_de_permissao_alas_do_armazem_normas> tipo_de_permissao_alas_do_armazem_normas { get; set; }
        public virtual ICollection<transferencia_entre_almoxarifado> transferencia_entre_almoxarifado { get; set; }
        public virtual ICollection<transferencia_entre_almoxarifado> transferencia_entre_almoxarifado1 { get; set; }
        public virtual ICollection<transferencia_entre_almoxarifado> transferencia_entre_almoxarifado2 { get; set; }
        public virtual ICollection<solicitacao_de_unificacao_divisao_de_talhoes> solicitacao_de_unificacao_divisao_de_talhoes { get; set; }
        public virtual ICollection<solicitacao_de_unificacao_divisao_de_talhoes> solicitacao_de_unificacao_divisao_de_talhoes1 { get; set; }
        public virtual ICollection<solicitacao_de_unificacao_divisao_de_talhoes> solicitacao_de_unificacao_divisao_de_talhoes2 { get; set; }
        public virtual ICollection<venda_prestacao_servico> venda_prestacao_servico { get; set; }
    }
}
