//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class grau_de_parentesco
    {
        public grau_de_parentesco()
        {
            this.dependentes_plano_de_saude = new HashSet<dependentes_plano_de_saude>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_DESCRICAO { get; set; }
        public decimal DECIMAL_PORCENTUAL { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual ICollection<dependentes_plano_de_saude> dependentes_plano_de_saude { get; set; }
    }
}
