//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo_da_carteira
    {
        public grupo_da_carteira()
        {
            this.carteira = new HashSet<carteira>();
            this.valor_diario_de_cada_carteira = new HashSet<valor_diario_de_cada_carteira>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_DESCRICAO { get; set; }
    
        public virtual ICollection<carteira> carteira { get; set; }
        public virtual ICollection<valor_diario_de_cada_carteira> valor_diario_de_cada_carteira { get; set; }
    }
}
