//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo_de_servico
    {
        public grupo_de_servico()
        {
            this.cliente = new HashSet<cliente>();
            this.comercial_ativo = new HashSet<comercial_ativo>();
            this.movimento_bancario = new HashSet<movimento_bancario>();
            this.portifolio_fornecedor = new HashSet<portifolio_fornecedor>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_DESCRICAO { get; set; }
        public int INT_ID_EMPRESA { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual ICollection<cliente> cliente { get; set; }
        public virtual ICollection<comercial_ativo> comercial_ativo { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual ICollection<movimento_bancario> movimento_bancario { get; set; }
        public virtual ICollection<portifolio_fornecedor> portifolio_fornecedor { get; set; }
    }
}
