//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo_reuniao
    {
        public grupo_reuniao()
        {
            this.cooperado = new HashSet<cooperado>();
            this.integrantes_grupo = new HashSet<integrantes_grupo>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_GRUPO { get; set; }
        public string TXT_CIDADE { get; set; }
        public Nullable<int> INT_ID_LIDER { get; set; }
        public string TXT_ESTADO { get; set; }
        public bool BOOL_REUNIOES_NUCLEOS { get; set; }
    
        public virtual ICollection<cooperado> cooperado { get; set; }
        public virtual ICollection<integrantes_grupo> integrantes_grupo { get; set; }
    }
}
