//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class instrucao_preparo
    {
        public instrucao_preparo()
        {
            this.instrucao_lote_resultado_para_gerar = new HashSet<instrucao_lote_resultado_para_gerar>();
            this.lote_instrucao = new HashSet<lote_instrucao>();
            this.normas_resultante_instrucao_preparo = new HashSet<normas_resultante_instrucao_preparo>();
            this.relacao_situacao_norma = new HashSet<relacao_situacao_norma>();
            this.resultado_rebeneficio = new HashSet<resultado_rebeneficio>();
        }
    
        public int INT_ID { get; set; }
        public Nullable<int> INT_ID_CONTRATO { get; set; }
        public int INT_ID_ALMOXARIFADO { get; set; }
        public string TXT_INSTRUCAO { get; set; }
        public int INT_ID_SIT_NORMA { get; set; }
        public bool BOOL_BATER_PILHA { get; set; }
        public Nullable<bool> BOOL_VENTILACAO { get; set; }
        public Nullable<bool> BOOL_CATACAO_ELETRONICA { get; set; }
        public Nullable<bool> BOOL_CATADOR_PEDRA { get; set; }
        public Nullable<bool> BOOL_REBENEFICIO_PENEIRAS { get; set; }
        public string TXT_PENEIRAS { get; set; }
        public string TXT_TIPO { get; set; }
        public Nullable<int> INT_DEFEITOS { get; set; }
        public string TXT_MOCA { get; set; }
        public string TXT_FUNDO { get; set; }
        public System.DateTime DATE_DATA_INSTRUCAO { get; set; }
        public string TXT_TIPO_SACARIA { get; set; }
        public string TXT_OIC { get; set; }
        public string TXT_OBS { get; set; }
        public string TXT_SAFRA { get; set; }
        public bool BOOL_TIPO_CAFE { get; set; }
        public Nullable<int> INT_ID_SUBTIPO { get; set; }
        public string CHAR_TIPO_SACARIA { get; set; }
        public Nullable<int> INT_ID_CLIENTE { get; set; }
        public bool BOOL_FLAG_ATIVO_EXCLUIDO { get; set; }
        public Nullable<int> INT_ID_AMOSTRA { get; set; }
        public Nullable<int> INT_ID_FUNCIONARIO { get; set; }
        public Nullable<System.DateTime> DATE_PREVISAO_TERMINO { get; set; }
        public bool BOOL_PRESTACAO_SERVICOS { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public Nullable<bool> BOOL_TIPO_CULTIVO_LOTE_QUE_SERA_GERADO { get; set; }
        public Nullable<bool> BOOL_TRANSICAO_LOTE_QUE_SERA_GERADO { get; set; }
        public Nullable<System.DateTime> DATE_INICIOU_CARREGAMENTO { get; set; }
        public Nullable<System.DateTime> DATE_FINALIZOU_CARREGAMENTO { get; set; }
        public Nullable<int> INT_ID_INICIOU_CARREGAMENTO { get; set; }
        public Nullable<int> INT_ID_FINALIZOU_CARREGAMENTO { get; set; }
    
        public virtual almoxarifado almoxarifado { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual composicao_amostra composicao_amostra { get; set; }
        public virtual contrato contrato { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        public virtual funcionario funcionario2 { get; set; }
        public virtual ICollection<instrucao_lote_resultado_para_gerar> instrucao_lote_resultado_para_gerar { get; set; }
        public virtual ICollection<lote_instrucao> lote_instrucao { get; set; }
        public virtual ICollection<normas_resultante_instrucao_preparo> normas_resultante_instrucao_preparo { get; set; }
        public virtual ICollection<relacao_situacao_norma> relacao_situacao_norma { get; set; }
        public virtual ICollection<resultado_rebeneficio> resultado_rebeneficio { get; set; }
        public virtual situacao_norma situacao_norma { get; set; }
        public virtual subtipo_norma subtipo_norma { get; set; }
    }
}
