//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class instituicao
    {
        public instituicao()
        {
            this.acc_com_hedge = new HashSet<acc_com_hedge>();
            this.hedge = new HashSet<hedge>();
            this.rolagem = new HashSet<rolagem>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_NOME_DA_INSTITUICAO { get; set; }
    
        public virtual ICollection<acc_com_hedge> acc_com_hedge { get; set; }
        public virtual ICollection<hedge> hedge { get; set; }
        public virtual ICollection<rolagem> rolagem { get; set; }
    }
}
