//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class integracao_contabil_lancamentos
    {
        public int INT_ID { get; set; }
        public int INT_ID_INTEGRACAO { get; set; }
        public int INT_ID_CONTAS_A_PAGAR_PLANO_DE_CONTAS { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual contas_a_pagar_plano_de_contas contas_a_pagar_plano_de_contas { get; set; }
        public virtual integracao_contabil integracao_contabil { get; set; }
    }
}
