//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class integrantes_grupo
    {
        public int INT_ID { get; set; }
        public int INT_ID_COOPERADO { get; set; }
        public int INT_ID_GRUPO_REUNIAO { get; set; }
    
        public virtual grupo_reuniao grupo_reuniao { get; set; }
    }
}
