//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class intervalo_da_forma_pagamento
    {
        public int INT_ID { get; set; }
        public int INT_INTERVALO { get; set; }
        public int INT_ID_FORMA_PAGAMENTO { get; set; }
        public bool BOOL_FLAG { get; set; }
    
        public virtual forma_de_pagamento forma_de_pagamento { get; set; }
    }
}
