//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class laboratorio
    {
        public laboratorio()
        {
            this.lote_para_analise_solo_foliar = new HashSet<lote_para_analise_solo_foliar>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_NOME { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual ICollection<lote_para_analise_solo_foliar> lote_para_analise_solo_foliar { get; set; }
    }
}
