//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class liquidacao_contrato_de_cambio
    {
        public liquidacao_contrato_de_cambio()
        {
            this.liquidacao_contrato_de_cambio_relacao_nf = new HashSet<liquidacao_contrato_de_cambio_relacao_nf>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_CONTRATO { get; set; }
        public int INT_ID_PG_REC_FLUXO_DE_CAIXA { get; set; }
        public decimal DECIMAL_VALOR_EM_DOLAR { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public int INT_ID_FUNCIONARIO { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
    
        public virtual contrato contrato { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual pagamento_recebimento_fluxo_de_caixa pagamento_recebimento_fluxo_de_caixa { get; set; }
        public virtual ICollection<liquidacao_contrato_de_cambio_relacao_nf> liquidacao_contrato_de_cambio_relacao_nf { get; set; }
    }
}
