//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_usuarios
    {
        public int INT_ID { get; set; }
        public int INT_ID_FUNC { get; set; }
        public string TXT_DESCRIÇÃO { get; set; }
        public System.DateTime DATE_DATA_E_HORA_DO_EVENTO { get; set; }
    
        public virtual funcionario funcionario { get; set; }
    }
}
