//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class lote_armazem_terceiros
    {
        public lote_armazem_terceiros()
        {
            this.alas_do_armazem_lotes = new HashSet<alas_do_armazem_lotes>();
            this.autorizacao_lotes = new HashSet<autorizacao_lotes>();
            this.lote_arm_terceiros_situacao_norma = new HashSet<lote_arm_terceiros_situacao_norma>();
            this.lote_producao_rastreabilidade = new HashSet<lote_producao_rastreabilidade>();
            this.lote_composicao = new HashSet<lote_composicao>();
            this.lotes_origem_do_produto = new HashSet<lotes_origem_do_produto>();
            this.referenciar_lotes_armazem_terceiros = new HashSet<referenciar_lotes_armazem_terceiros>();
            this.lote_instrucao = new HashSet<lote_instrucao>();
            this.solicitacao_de_amostra_lote = new HashSet<solicitacao_de_amostra_lote>();
        }
    
        public int INT_ID { get; set; }
        public Nullable<int> INT_ID_CARREGAMENTO_PARA_TERC { get; set; }
        public string TXT_LOTE_GERADO { get; set; }
        public Nullable<float> FLOAT_PESO_LIQUIDO { get; set; }
        public decimal FLOAT_SACAS_TOTAL { get; set; }
        public System.DateTime DATE_DATA_ENTRADA { get; set; }
        public float FLOAT_VALOR_ENTRADA { get; set; }
        public string TXT_SAFRA { get; set; }
        public bool BOOL_TIPO_CAFE { get; set; }
        public Nullable<bool> BOOL_ATIVO { get; set; }
        public bool BOOL_MEXER { get; set; }
        public Nullable<int> INT_ID_SUBTIPO { get; set; }
        public bool BOOL_TRANSICAO { get; set; }
        public string TXT_MOTIVO_DE_NAO_MEXER { get; set; }
    
        public virtual ICollection<alas_do_armazem_lotes> alas_do_armazem_lotes { get; set; }
        public virtual ICollection<autorizacao_lotes> autorizacao_lotes { get; set; }
        public virtual carregamento_para_armazem_terceiros carregamento_para_armazem_terceiros { get; set; }
        public virtual ICollection<lote_arm_terceiros_situacao_norma> lote_arm_terceiros_situacao_norma { get; set; }
        public virtual ICollection<lote_producao_rastreabilidade> lote_producao_rastreabilidade { get; set; }
        public virtual ICollection<lote_composicao> lote_composicao { get; set; }
        public virtual ICollection<lotes_origem_do_produto> lotes_origem_do_produto { get; set; }
        public virtual ICollection<referenciar_lotes_armazem_terceiros> referenciar_lotes_armazem_terceiros { get; set; }
        public virtual ICollection<lote_instrucao> lote_instrucao { get; set; }
        public virtual ICollection<solicitacao_de_amostra_lote> solicitacao_de_amostra_lote { get; set; }
        public virtual subtipo_norma subtipo_norma { get; set; }
    }
}
