//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class lote_resultado_rebeneficio
    {
        public lote_resultado_rebeneficio()
        {
            this.alas_do_armazem_lotes = new HashSet<alas_do_armazem_lotes>();
            this.autorizacao_lotes = new HashSet<autorizacao_lotes>();
            this.lote_composicao = new HashSet<lote_composicao>();
            this.lote_instrucao = new HashSet<lote_instrucao>();
            this.lote_origem_do_result_reb = new HashSet<lote_origem_do_result_reb>();
            this.lote_producao_rastreabilidade = new HashSet<lote_producao_rastreabilidade>();
            this.lotes_origem_do_produto = new HashSet<lotes_origem_do_produto>();
            this.lote_resultado_rebeneficio_situacao_norma = new HashSet<lote_resultado_rebeneficio_situacao_norma>();
            this.solicitacao_de_amostra_lote = new HashSet<solicitacao_de_amostra_lote>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_RESULTADO_REBENEFICIO { get; set; }
        public string TXT_LOTE { get; set; }
        public decimal FLOAT_QTD_SACAS { get; set; }
        public float FLOAT_PESO_LIQUIDO { get; set; }
        public Nullable<float> FLOAT_PONTUACAO { get; set; }
        public string CHAR_QUALIDADE { get; set; }
        public string TXT_TIPO_CAFE { get; set; }
        public string TXT_PENEIRA { get; set; }
        public bool BOOL_TIPO_CAFE { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public bool BOOL_TRANSICAO { get; set; }
        public Nullable<int> INT_SUBTIPO { get; set; }
        public bool BOOL_MEXER { get; set; }
        public string TXT_MOTIVO_DE_NAO_MEXER { get; set; }
        public Nullable<int> INT_ID_INSTRUCAO_TIPO_LOTE { get; set; }
        public Nullable<int> INT_ID_BEBIDA { get; set; }
        public Nullable<decimal> DECIMAL_DEFEITOS { get; set; }
        public Nullable<int> INT_ID_TIPO { get; set; }
        public Nullable<decimal> DECIMAL_UMIDADE { get; set; }
        public Nullable<decimal> DECIMAL_VAZAMENTO { get; set; }
        public string TXT_OBS { get; set; }
        public string TXT_CODIGO_DE_BARRAS { get; set; }
    
        public virtual ICollection<alas_do_armazem_lotes> alas_do_armazem_lotes { get; set; }
        public virtual ICollection<autorizacao_lotes> autorizacao_lotes { get; set; }
        public virtual bebida bebida { get; set; }
        public virtual instrucao_lote_resultado_para_gerar instrucao_lote_resultado_para_gerar { get; set; }
        public virtual ICollection<lote_composicao> lote_composicao { get; set; }
        public virtual ICollection<lote_instrucao> lote_instrucao { get; set; }
        public virtual ICollection<lote_origem_do_result_reb> lote_origem_do_result_reb { get; set; }
        public virtual ICollection<lote_producao_rastreabilidade> lote_producao_rastreabilidade { get; set; }
        public virtual tipo_cafe_rebeneficiado tipo_cafe_rebeneficiado { get; set; }
        public virtual ICollection<lotes_origem_do_produto> lotes_origem_do_produto { get; set; }
        public virtual ICollection<lote_resultado_rebeneficio_situacao_norma> lote_resultado_rebeneficio_situacao_norma { get; set; }
        public virtual resultado_rebeneficio resultado_rebeneficio { get; set; }
        public virtual ICollection<solicitacao_de_amostra_lote> solicitacao_de_amostra_lote { get; set; }
        public virtual subtipo_norma subtipo_norma { get; set; }
    }
}
