//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class lotes_origem_do_produto
    {
        public int INT_ID { get; set; }
        public int INT_ID_ORIGEM { get; set; }
        public Nullable<int> INT_ID_LOTE_ARM_TERCEIROS { get; set; }
        public decimal FLOAT_QTD_SACAS { get; set; }
        public Nullable<int> INT_ID_LOTE_REBENEFICIADO { get; set; }
        public string FLAG_TIPO_LOTE { get; set; }
        public int INT_ID_LOTE_ENTRADA { get; set; }
        public string TXT_FLAG_TIPO_VENDA { get; set; }
    
        public virtual cadastro_entrada cadastro_entrada { get; set; }
        public virtual lote_armazem_terceiros lote_armazem_terceiros { get; set; }
        public virtual lote_resultado_rebeneficio lote_resultado_rebeneficio { get; set; }
        public virtual origem_do_produto origem_do_produto { get; set; }
    }
}
