//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class lote_producao_rastreabilidade
    {
        public int INT_ID { get; set; }
        public int INT_ID_LOTE_PRODUTO_GERADO { get; set; }
        public Nullable<int> INT_ID_CADASTRO_ENTRADA { get; set; }
        public Nullable<int> INT_ID_LOTE_ARMAZEM_TERCEIRO { get; set; }
        public Nullable<int> INT_ID_LOTE_RESULTADO_REBENEFICIO { get; set; }
        public int INT_ID_LOTE_PRODUTO_ORIGEM { get; set; }
        public bool BOOL_MATERIA_PRIMA { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public Nullable<int> INT_ID_ORIGEM_DO_PRODUTO { get; set; }
        public decimal DECIMAL_QTD_KG { get; set; }
    
        public virtual cadastro_entrada cadastro_entrada { get; set; }
        public virtual lote_armazem_terceiros lote_armazem_terceiros { get; set; }
        public virtual lote_produto lote_produto { get; set; }
        public virtual lote_produto lote_produto1 { get; set; }
        public virtual lote_resultado_rebeneficio lote_resultado_rebeneficio { get; set; }
        public virtual origem_do_produto origem_do_produto { get; set; }
    }
}
