//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class lote_para_analise_solo_foliar
    {
        public lote_para_analise_solo_foliar()
        {
            this.amostra_solo_foliar_lote = new HashSet<amostra_solo_foliar_lote>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_LOTE { get; set; }
        public System.DateTime DATE_ENVIO { get; set; }
        public int INT_ID_ENVIO { get; set; }
        public System.DateTime DATE_CADASTRO { get; set; }
        public Nullable<System.DateTime> DATE_ALTEROU { get; set; }
        public Nullable<System.DateTime> DATE_EXLCUIU { get; set; }
        public int INT_ID_CADASTRO { get; set; }
        public Nullable<int> INT_ID_ALTEROU { get; set; }
        public Nullable<int> INT_ID_EXCLUIU { get; set; }
        public int INT_ID_LABORATORIO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public string TXT_OBS { get; set; }
    
        public virtual ICollection<amostra_solo_foliar_lote> amostra_solo_foliar_lote { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        public virtual funcionario funcionario2 { get; set; }
        public virtual funcionario funcionario3 { get; set; }
        public virtual laboratorio laboratorio { get; set; }
    }
}
