//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class maquinario
    {
        public maquinario()
        {
            this.ordem_de_producao = new HashSet<ordem_de_producao>();
            this.ordem_de_producao1 = new HashSet<ordem_de_producao>();
            this.ordem_de_producao_embalagens = new HashSet<ordem_de_producao_embalagens>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_DESCRICAO { get; set; }
        public int INT_ID_EMPRESA { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public string CHAR_TIPO_MAQUINARIO { get; set; }
        public bool BOOL_CONTAR_TEMPO_MOEGA { get; set; }
    
        public virtual empresa empresa { get; set; }
        public virtual ICollection<ordem_de_producao> ordem_de_producao { get; set; }
        public virtual ICollection<ordem_de_producao> ordem_de_producao1 { get; set; }
        public virtual ICollection<ordem_de_producao_embalagens> ordem_de_producao_embalagens { get; set; }
    }
}
