//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class modalidade_entrega
    {
        public modalidade_entrega()
        {
            this.contrato = new HashSet<contrato>();
            this.cotacao_compra_item = new HashSet<cotacao_compra_item>();
            this.cotacao_resultado_itens = new HashSet<cotacao_resultado_itens>();
            this.fechamento_mercado_futuro = new HashSet<fechamento_mercado_futuro>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_DESCRICAO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public int INT_ID_EMPRESA { get; set; }
    
        public virtual ICollection<contrato> contrato { get; set; }
        public virtual ICollection<cotacao_compra_item> cotacao_compra_item { get; set; }
        public virtual ICollection<cotacao_resultado_itens> cotacao_resultado_itens { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual ICollection<fechamento_mercado_futuro> fechamento_mercado_futuro { get; set; }
    }
}
