//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class motorista
    {
        public motorista()
        {
            this.agendamento_carga_descarga = new HashSet<agendamento_carga_descarga>();
            this.contrato = new HashSet<contrato>();
            this.motorista_autorizacao = new HashSet<motorista_autorizacao>();
            this.nota_fiscal = new HashSet<nota_fiscal>();
            this.pedido_faturamento = new HashSet<pedido_faturamento>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_NOME { get; set; }
        public string TXT_CPF { get; set; }
        public string TXT_PLACA { get; set; }
        public string TXT_NOME_FANTASIA { get; set; }
        public bool BOOL_PF_PJ { get; set; }
        public string TXT_RUA { get; set; }
        public string TXT_MUNICIPIO { get; set; }
        public string TXT_UF { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public string TXT_UF_PLACA { get; set; }
        public string TXT_IE { get; set; }
        public string TXT_NUMERO { get; set; }
        public string TXT_BAIRRO { get; set; }
        public string TXT_ANTT { get; set; }
    
        public virtual ICollection<agendamento_carga_descarga> agendamento_carga_descarga { get; set; }
        public virtual ICollection<contrato> contrato { get; set; }
        public virtual ICollection<motorista_autorizacao> motorista_autorizacao { get; set; }
        public virtual ICollection<nota_fiscal> nota_fiscal { get; set; }
        public virtual ICollection<pedido_faturamento> pedido_faturamento { get; set; }
    }
}
