//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class motorista_autorizacao
    {
        public int INT_ID { get; set; }
        public int INT_ID_MOTORISTA { get; set; }
        public Nullable<int> INT_ID_AUTORIZACAO { get; set; }
        public string TXT_PLACA_CAVALO { get; set; }
        public string TXT_PLACA_BUG { get; set; }
        public bool BOOL_ATIVO_OU_EXCLUIDO { get; set; }
        public float FLOAT_QTD_SCS { get; set; }
        public string TXT_CONTAINER { get; set; }
        public string TXT_LACRE { get; set; }
        public Nullable<int> INT_TARA { get; set; }
        public string TXT_OBS { get; set; }
        public Nullable<int> INT_ID_AUTORIZACAO_GENERICA { get; set; }
    
        public virtual autorizacao_generica autorizacao_generica { get; set; }
        public virtual autorizacao_venda_exp autorizacao_venda_exp { get; set; }
        public virtual motorista motorista { get; set; }
    }
}
