//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimento_bancario
    {
        public movimento_bancario()
        {
            this.baixa_valor_adiantado = new HashSet<baixa_valor_adiantado>();
            this.contas_a_pagar_e_receber = new HashSet<contas_a_pagar_e_receber>();
            this.contas_a_pagar_planejamento = new HashSet<contas_a_pagar_planejamento>();
            this.contas_a_pagar_plano_de_contas = new HashSet<contas_a_pagar_plano_de_contas>();
            this.movimento_bancario1 = new HashSet<movimento_bancario>();
            this.pagamento_emprestimo = new HashSet<pagamento_emprestimo>();
            this.rastrear_transferencias_entre_contas = new HashSet<rastrear_transferencias_entre_contas>();
            this.rastrear_transferencias_entre_contas1 = new HashSet<rastrear_transferencias_entre_contas>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_BANCO_EMPRESA { get; set; }
        public decimal DECIMAL_VALOR_TOTAL { get; set; }
        public Nullable<System.DateTime> DATE_OPERACAO { get; set; }
        public string TXT_DOC { get; set; }
        public string TXT_HISTORICO_CONTABIL { get; set; }
        public string TXT_TIPO_MOVIMENTO { get; set; }
        public bool BOOL_RECEBIMENTO_PAGAMENTO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public Nullable<int> INT_ID_EMPRESTIMO { get; set; }
        public Nullable<int> INT_ID_BANCO_COOPERADO { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public Nullable<int> INT_ID_RECIBO { get; set; }
        public int INT_ID_FUNCIONARIO { get; set; }
        public bool BOOL_TRANSFERENCIA_CHEQUE { get; set; }
        public Nullable<bool> BOOL_CHEQUE { get; set; }
        public bool BOOL_ADIANTAMENTO { get; set; }
        public Nullable<int> INT_ID_FORNECEDOR { get; set; }
        public decimal DECIMAL_JUROS { get; set; }
        public decimal DECIMAL_MULTA { get; set; }
        public Nullable<int> INT_ID_TRANSFERENCIA { get; set; }
        public Nullable<int> INT_ID_PAGAMENTO { get; set; }
        public decimal DECIMAL_DESCONTO { get; set; }
        public decimal DECIMAL_VALOR { get; set; }
        public Nullable<int> INT_ID_BANCO_FORNECEDOR { get; set; }
        public Nullable<int> INT_ID_ACC { get; set; }
        public Nullable<System.DateTime> DATE_EMISSAO_DO_CHEQUE { get; set; }
        public Nullable<int> INT_ID_BANCO_EMPRESA_DESTINO_TRANSFERENCIA { get; set; }
        public Nullable<int> INT_ID_TARIFA_ACC { get; set; }
        public Nullable<int> INT_ID_GRUPO_DE_SERVICO { get; set; }
        public Nullable<int> INT_ID_COOPERADO { get; set; }
        public decimal DECIMAL_ACRESCIMO { get; set; }
        public bool BOOL_NAO_PRECISA_LANCAR_PLANO_DE_CONTAS { get; set; }
        public bool BOOL_JUROS { get; set; }
        public string TXT_FTIID { get; set; }
        public string TXT_CHECKNUM { get; set; }
        public Nullable<System.DateTime> DATE_CONCILIACAO { get; set; }
        public Nullable<int> INT_ID_RESPONSAVEL_PELA_CONCILIACAO { get; set; }
        public string TXT_OBS { get; set; }
        public bool BOOL_CONSIDERAR_TRANSFERENCIA { get; set; }
    
        public virtual acc_com_hedge acc_com_hedge { get; set; }
        public virtual acc_com_hedge acc_com_hedge1 { get; set; }
        public virtual ICollection<baixa_valor_adiantado> baixa_valor_adiantado { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual cliente_conta_bancaria cliente_conta_bancaria { get; set; }
        public virtual ICollection<contas_a_pagar_e_receber> contas_a_pagar_e_receber { get; set; }
        public virtual ICollection<contas_a_pagar_planejamento> contas_a_pagar_planejamento { get; set; }
        public virtual ICollection<contas_a_pagar_plano_de_contas> contas_a_pagar_plano_de_contas { get; set; }
        public virtual contas_bancarias_empresa contas_bancarias_empresa { get; set; }
        public virtual cooperado cooperado { get; set; }
        public virtual dados_bancarios dados_bancarios { get; set; }
        public virtual emprestimos emprestimos { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        public virtual grupo_de_servico grupo_de_servico { get; set; }
        public virtual ICollection<movimento_bancario> movimento_bancario1 { get; set; }
        public virtual movimento_bancario movimento_bancario2 { get; set; }
        public virtual pagamento_recebimento pagamento_recebimento { get; set; }
        public virtual recibo recibo { get; set; }
        public virtual ICollection<pagamento_emprestimo> pagamento_emprestimo { get; set; }
        public virtual ICollection<rastrear_transferencias_entre_contas> rastrear_transferencias_entre_contas { get; set; }
        public virtual ICollection<rastrear_transferencias_entre_contas> rastrear_transferencias_entre_contas1 { get; set; }
    }
}
