//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class normas_resultante_instrucao_preparo
    {
        public int INT_ID { get; set; }
        public int INT_ID_INSTRUCAO { get; set; }
        public int INT_ID_SITUACAO_NORMA { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual instrucao_preparo instrucao_preparo { get; set; }
        public virtual situacao_norma situacao_norma { get; set; }
    }
}
