//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class norma_talhao
    {
        public norma_talhao()
        {
            this.norma_talhao_historico = new HashSet<norma_talhao_historico>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_SITUACAO { get; set; }
        public int ID_TALHAO { get; set; }
        public bool BOOL_ATIVO_EXCLUIDO { get; set; }
        public Nullable<int> INT_ID_LANCAMENTO { get; set; }
        public Nullable<System.DateTime> DATE_LANCAMENTO { get; set; }
        public Nullable<int> INT_ID_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DATE_EXCLUSAO { get; set; }
    
        public virtual funcionario funcionario { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        public virtual talhao talhao { get; set; }
        public virtual situacao_norma situacao_norma { get; set; }
        public virtual ICollection<norma_talhao_historico> norma_talhao_historico { get; set; }
    }
}
