//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class nota_fiscal
    {
        public nota_fiscal()
        {
            this.contas_a_pagar_e_receber = new HashSet<contas_a_pagar_e_receber>();
            this.contas_a_pagar_plano_de_contas = new HashSet<contas_a_pagar_plano_de_contas>();
            this.fluxo_de_caixa = new HashSet<fluxo_de_caixa>();
            this.movimentos_produtos_contabeis = new HashSet<movimentos_produtos_contabeis>();
            this.nota_fiscal1 = new HashSet<nota_fiscal>();
            this.notas_canceladas = new HashSet<notas_canceladas>();
        }
    
        public int INT_ID { get; set; }
        public Nullable<int> INT_ID_VENDA_PRESTACAO { get; set; }
        public int INT_NF { get; set; }
        public decimal DECIMAL_VALOR_TOTAL { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public int INT_ID_FUNCIONARIO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public bool BOOL_VENDA_RETORNO { get; set; }
        public string TXT_INFORMACOES_ADD { get; set; }
        public Nullable<int> INT_ID_CFOP { get; set; }
        public decimal DECIMAL_BC_ICMS { get; set; }
        public decimal DECIMAL_ICMS { get; set; }
        public decimal DECIMAL_ICMSST { get; set; }
        public decimal DECIMAL_PIS { get; set; }
        public decimal DECIMAL_PISST { get; set; }
        public decimal DECIMAL_COFINS { get; set; }
        public decimal DECIMAL_COFINSST { get; set; }
        public decimal DECIMAL_IPI { get; set; }
        public decimal DECIMAL_ICMS_PARTILHADO { get; set; }
        public decimal DECIMAL_FRETE { get; set; }
        public decimal DECIMAL_DESCONTO { get; set; }
        public decimal DECIMAL_JUROS { get; set; }
        public decimal DECIMAL_SEGURO { get; set; }
        public decimal DECIMAL_MULTA { get; set; }
        public decimal DECIMAL_VALOR_LIQUIDO { get; set; }
        public string TXT_MODALIDADE_FRETE { get; set; }
        public int INT_INDEX_MODALIDADE_FRETE { get; set; }
        public Nullable<int> INT_ID_MOTORISTA_TRANSPORTADOR { get; set; }
        public string TXT_PLACA { get; set; }
        public string TXT_UF_PLACA { get; set; }
        public string TXT_ANTT { get; set; }
        public int INT_VOLUME { get; set; }
        public string TXT_ESPECIE_DO_ESPECIE { get; set; }
        public decimal DECIMAL_PESO_LIQUIDO { get; set; }
        public decimal DECIMAL_PESO_BRUTO { get; set; }
        public int INT_ID_EMPRESA { get; set; }
        public Nullable<int> INT_ID_AUTORIZACAO_DE_CARREGAMENTO { get; set; }
        public bool BOOL_COMPLEMENTACAO { get; set; }
        public Nullable<int> INT_ID_NF_REFERENCIADA { get; set; }
        public string TXT_CHAVE_DE_ACESSO { get; set; }
        public bool BOOL_CANCELADA_NFEMAIL { get; set; }
        public string TXT_STATUS { get; set; }
        public Nullable<int> INT_NR_PRE_NOTA { get; set; }
        public Nullable<int> INT_COLOCOU_PARA_TRANSMITIR { get; set; }
        public Nullable<System.DateTime> DATE_TRANSMISSAO { get; set; }
        public string CHAR_TIPO_NOTA { get; set; }
        public string TXT_TIPO_FINALIDADE_NOTA { get; set; }
        public Nullable<int> INT_ID_CONFIGURACAO_NOTA_FILIAL { get; set; }
    
        public virtual autorizacao_generica autorizacao_generica { get; set; }
        public virtual cfop cfop { get; set; }
        public virtual configuracao_nota_filial configuracao_nota_filial { get; set; }
        public virtual ICollection<contas_a_pagar_e_receber> contas_a_pagar_e_receber { get; set; }
        public virtual ICollection<contas_a_pagar_plano_de_contas> contas_a_pagar_plano_de_contas { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual ICollection<fluxo_de_caixa> fluxo_de_caixa { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        public virtual motorista motorista { get; set; }
        public virtual ICollection<movimentos_produtos_contabeis> movimentos_produtos_contabeis { get; set; }
        public virtual ICollection<nota_fiscal> nota_fiscal1 { get; set; }
        public virtual nota_fiscal nota_fiscal2 { get; set; }
        public virtual venda_prestacao_servico venda_prestacao_servico { get; set; }
        public virtual ICollection<notas_canceladas> notas_canceladas { get; set; }
    }
}
