//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordem_reensaque
    {
        public ordem_reensaque()
        {
            this.ordem_reensaque_lotes = new HashSet<ordem_reensaque_lotes>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_NR_ORDEM { get; set; }
        public string TXT_SAFRA { get; set; }
        public int INT_ID_RESPONSAVEL { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public int INT_ID_TIPO_SACARIA { get; set; }
        public Nullable<int> INT_ID_CONTRATO { get; set; }
        public int INT_ID_LANCOU { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public Nullable<int> INT_ID_ALTEROU { get; set; }
        public Nullable<System.DateTime> DATE_ALTEROU { get; set; }
        public Nullable<int> INT_ID_EXCLUIU { get; set; }
        public Nullable<System.DateTime> DATE_EXCLUIU { get; set; }
        public string TXT_OBS { get; set; }
        public string TXT_STATUS { get; set; }
        public System.DateTime DATE_ORDEM { get; set; }
    
        public virtual contrato contrato { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        public virtual funcionario funcionario2 { get; set; }
        public virtual funcionario funcionario3 { get; set; }
        public virtual tipo_sacaria tipo_sacaria { get; set; }
        public virtual ICollection<ordem_reensaque_lotes> ordem_reensaque_lotes { get; set; }
    }
}
