//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordem_de_producao_resultado
    {
        public ordem_de_producao_resultado()
        {
            this.lote_produto = new HashSet<lote_produto>();
            this.ordem_de_producao_produtos_utilizados = new HashSet<ordem_de_producao_produtos_utilizados>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_OP { get; set; }
        public decimal DECIMAL_PERCA { get; set; }
        public System.DateTime DATE_RESULTADO { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public int INT_ID_FUNCIONARIO { get; set; }
        public int INT_ID_ALMOXARIFADO { get; set; }
        public int INT_ID_EMPRESA { get; set; }
        public decimal DECIMAL_VLR_TOTAL { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public string TXT_OBS { get; set; }
        public Nullable<int> INT_ID_REVISAO_POP { get; set; }
    
        public virtual almoxarifado almoxarifado { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual ICollection<lote_produto> lote_produto { get; set; }
        public virtual ordem_de_producao ordem_de_producao { get; set; }
        public virtual ICollection<ordem_de_producao_produtos_utilizados> ordem_de_producao_produtos_utilizados { get; set; }
        public virtual revisoes_pop revisoes_pop { get; set; }
    }
}
