//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordem_de_producao_situacaonorma
    {
        public int INT_ID { get; set; }
        public int INT_ID_ORDEM_DE_PRODUCAO { get; set; }
        public int INT_ID_SITUACAO_NORMA { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual ordem_de_producao ordem_de_producao { get; set; }
        public virtual situacao_norma situacao_norma { get; set; }
    }
}
