//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordem_reensaque_lotes
    {
        public int INT_ID { get; set; }
        public int INT_ID_ORDEM_REENSAQUE { get; set; }
        public Nullable<int> INT_ID_CADASTRO_ENTRADA { get; set; }
        public Nullable<int> INT_ID_LOTE_ARMAZEN_TERCEIROS { get; set; }
        public Nullable<int> INT_ID_LOTE_RESULTADO_REBENEFICIO { get; set; }
        public decimal DECIMAL_SCS { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public int INT_ID_LANCOU { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public Nullable<int> INT_ID_ALTEROU { get; set; }
        public Nullable<System.DateTime> DATE_ALTEROU { get; set; }
        public Nullable<int> INT_ID_EXCLUIU { get; set; }
        public Nullable<System.DateTime> DATE_EXCLUIU { get; set; }
    
        public virtual cadastro_entrada cadastro_entrada { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        public virtual funcionario funcionario2 { get; set; }
        public virtual lote_armazem_terceiros lote_armazem_terceiros { get; set; }
        public virtual lote_resultado_rebeneficio lote_resultado_rebeneficio { get; set; }
        public virtual ordem_reensaque ordem_reensaque { get; set; }
    }
}
