//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class origem_do_produto
    {
        public origem_do_produto()
        {
            this.lote_producao_rastreabilidade = new HashSet<lote_producao_rastreabilidade>();
            this.lotes_origem_do_produto = new HashSet<lotes_origem_do_produto>();
            this.movimentos_produtos_contabeis = new HashSet<movimentos_produtos_contabeis>();
            this.origem_do_produto_nota_fiscal = new HashSet<origem_do_produto_nota_fiscal>();
        }
    
        public int INT_ID { get; set; }
        public System.DateTime DATE_DATA_ORIGEM { get; set; }
        public Nullable<int> INT_ID_CONTRATO { get; set; }
        public int INT_ID_AUTORIZACAO_EXP_VENDA_INT { get; set; }
        public Nullable<int> INT_ID_RESPONSAVEL { get; set; }
        public string TXT_OBS { get; set; }
        public bool BOOL_FLAG_ORIGEM_FINALIZADA { get; set; }
        public Nullable<int> INT_ID_REVISAO_POP { get; set; }
    
        public virtual autorizacao_generica autorizacao_generica { get; set; }
        public virtual contrato contrato { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual ICollection<lote_producao_rastreabilidade> lote_producao_rastreabilidade { get; set; }
        public virtual ICollection<lotes_origem_do_produto> lotes_origem_do_produto { get; set; }
        public virtual ICollection<movimentos_produtos_contabeis> movimentos_produtos_contabeis { get; set; }
        public virtual revisoes_pop revisoes_pop { get; set; }
        public virtual ICollection<origem_do_produto_nota_fiscal> origem_do_produto_nota_fiscal { get; set; }
    }
}
