//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ouvidoria
    {
        public ouvidoria()
        {
            this.ouvidoria_mensagem = new HashSet<ouvidoria_mensagem>();
        }
    
        public int INT_ID { get; set; }
        public Nullable<int> INT_ID_SOLICITANTE { get; set; }
        public string TXT_SETOR { get; set; }
        public bool BOOL_ANONIMO { get; set; }
        public string TXT_DESCRICAO { get; set; }
        public string TXT_STATUS { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public bool BOOL_GENERO { get; set; }
        public bool BOOL_QUEIXA { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public bool BOOL_RH { get; set; }
    
        public virtual funcionario funcionario { get; set; }
        public virtual ICollection<ouvidoria_mensagem> ouvidoria_mensagem { get; set; }
    }
}
