//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class padrao_de_imposto_por_cfop
    {
        public padrao_de_imposto_por_cfop()
        {
            this.configuracao_nota_filial = new HashSet<configuracao_nota_filial>();
            this.pedido_faturamento_produto = new HashSet<pedido_faturamento_produto>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_CFOP { get; set; }
        public Nullable<int> INT_ID_GRUPO_DE_IMPOSTO { get; set; }
        public int INT_ID_PRODUTO { get; set; }
        public string TXT_CST_ICMS { get; set; }
        public string TXT_ORIGEM { get; set; }
        public decimal DECIMAL_ALIQUOTA_ICMS { get; set; }
        public decimal DECIMAL_REDUCAO_BC_ICMS { get; set; }
        public string TXT_MODALIDADE_DA_BC { get; set; }
        public string TXT_UF { get; set; }
        public decimal DECIMAL_BC_OP_PROPIRA { get; set; }
        public string TXT_MODALIDADE_DE_DET_DA_BC_ICMSST { get; set; }
        public decimal DECIMAL_ALIQUOTA_ICMSST { get; set; }
        public decimal DECIMAL_MARGEM_VALOR_ADIC { get; set; }
        public decimal DECIMAL_REDUCAO_BC_ICMS_ST { get; set; }
        public string TXT_ICMS_DESONERADO { get; set; }
        public string TXT_IPI_CST { get; set; }
        public bool BOOL_TIPO_CALC_IPI { get; set; }
        public decimal DECIMAL_IPI_ALIQUOTA { get; set; }
        public decimal DECIMAL_IPI_VLR_UNITARIO { get; set; }
        public string TXT_IPI_CODIGO_ENQUADRAMENTO { get; set; }
        public string TXT_PIS_CST { get; set; }
        public bool BOOL_TIPO_CALC_PIS { get; set; }
        public decimal DECIMAL_ALIQUOTA_PIS { get; set; }
        public decimal DECIMAL_PIS_VLR_UNI { get; set; }
        public bool BOOL_PISST { get; set; }
        public bool BOOL_TIPO_CALC_PISST { get; set; }
        public decimal DECIMAL_ALIQUOTA_PISST { get; set; }
        public decimal DECIMAL_PISST_VLR_UNI { get; set; }
        public string TXT_COFINS_CST { get; set; }
        public bool BOOL_TIPO_CALC_COFINS { get; set; }
        public decimal DECIMAL_ALIQUOTA_COFINS { get; set; }
        public decimal DECIMAL_COFINS_VLR_UNI { get; set; }
        public bool BOOL_COFINSST { get; set; }
        public bool BOOL_TIPO_CALC_COFINSST { get; set; }
        public decimal DECIMAL_ALIQUOTA_COFINSST { get; set; }
        public decimal DECIMAL_COFINSST_VLR_UNI { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public bool BOOL_DIFAL { get; set; }
        public int INT_INDEX_CST_ICMS { get; set; }
        public int INT_INDEX_CST_PIS { get; set; }
        public int INT_INDEX_CST_COFINS { get; set; }
        public int INT_INDEX_CST_IPI { get; set; }
        public int INT_INDEX_ORIGEM { get; set; }
        public int INT_INDEX_MODALIDADE_BC_ICMS { get; set; }
        public int INT_INDEX_MODALIDADE_BC_ICMS_ST { get; set; }
        public int INT_INDEX_MOTIVO_DESONERACAO_ICMS { get; set; }
        public string TXT_NATUREZA_DA_RECEITA { get; set; }
        public Nullable<int> INT_ID_INFORMACAO_ADICIONAL { get; set; }
        public decimal DECIMAL_VALOR { get; set; }
    
        public virtual cfop cfop { get; set; }
        public virtual ICollection<configuracao_nota_filial> configuracao_nota_filial { get; set; }
        public virtual grupo_de_imposto grupo_de_imposto { get; set; }
        public virtual informacao_adicional informacao_adicional { get; set; }
        public virtual produtos_contabeis produtos_contabeis { get; set; }
        public virtual ICollection<pedido_faturamento_produto> pedido_faturamento_produto { get; set; }
    }
}
