//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagamento_recebimento_fluxo_de_caixa
    {
        public pagamento_recebimento_fluxo_de_caixa()
        {
            this.contas_a_pagar_plano_de_contas = new HashSet<contas_a_pagar_plano_de_contas>();
            this.liquidacao_contrato_de_cambio = new HashSet<liquidacao_contrato_de_cambio>();
            this.premio_ft = new HashSet<premio_ft>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_FLUXO_DE_CAIXA { get; set; }
        public int INT_ID_PAGAMENTO { get; set; }
        public decimal DECIMAL_TOTAL { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public bool BOOL_PG_RECEBIMENTO { get; set; }
        public decimal DECIMAL_DESCONTO { get; set; }
        public decimal DECIMAL_COMISSAO { get; set; }
        public decimal DECIMAL_JUROS { get; set; }
    
        public virtual ICollection<contas_a_pagar_plano_de_contas> contas_a_pagar_plano_de_contas { get; set; }
        public virtual fluxo_de_caixa fluxo_de_caixa { get; set; }
        public virtual ICollection<liquidacao_contrato_de_cambio> liquidacao_contrato_de_cambio { get; set; }
        public virtual pagamento_recebimento pagamento_recebimento { get; set; }
        public virtual ICollection<premio_ft> premio_ft { get; set; }
    }
}
