//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagamento_emprestimo
    {
        public pagamento_emprestimo()
        {
            this.premio_ft = new HashSet<premio_ft>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_PARCELAS { get; set; }
        public Nullable<int> INT_ID_RECIBO { get; set; }
        public decimal DECIMAL_PG { get; set; }
        public bool BOOL_DESC_CAFE { get; set; }
        public int INT_ID_FUNC { get; set; }
        public decimal DECIMAL_JUROS { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public Nullable<int> INT_ID_MOVIMENTO { get; set; }
        public Nullable<bool> BOOL_DESCONTAR_AVALISTA { get; set; }
        public Nullable<int> INT_ID_AVALISTA_PAGADOR_RECEBIMENTO_AVULSO { get; set; }
    
        public virtual cooperado cooperado { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual movimento_bancario movimento_bancario { get; set; }
        public virtual parcela_emprestimo parcela_emprestimo { get; set; }
        public virtual recibo recibo { get; set; }
        public virtual ICollection<premio_ft> premio_ft { get; set; }
    }
}
