//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagamento_recebimento
    {
        public pagamento_recebimento()
        {
            this.movimento_bancario = new HashSet<movimento_bancario>();
            this.pagamento_recebimento_fluxo_de_caixa = new HashSet<pagamento_recebimento_fluxo_de_caixa>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_FUNCIONARIO { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public string TXT_OBS { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public bool BOOL_ADIANTAMENTO { get; set; }
        public bool BOOL_PG_RECEBIMENTO { get; set; }
        public bool BOOL_CONTRATO_DE_CAMBIO { get; set; }
        public Nullable<System.DateTime> DATE_OPERACAO { get; set; }
    
        public virtual ICollection<movimento_bancario> movimento_bancario { get; set; }
        public virtual ICollection<pagamento_recebimento_fluxo_de_caixa> pagamento_recebimento_fluxo_de_caixa { get; set; }
    }
}
