//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido_faturamento_parcelas
    {
        public int INT_ID { get; set; }
        public int INT_ID_TIPO_DE_PAGAMENTO { get; set; }
        public System.DateTime DATE_VENCIMENTO { get; set; }
        public decimal DECIMAL_VALOR { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public int INT_ID_PEDIDO_FATURAMENTO { get; set; }
    
        public virtual pedido_faturamento pedido_faturamento { get; set; }
        public virtual tipo_de_pagamento tipo_de_pagamento { get; set; }
    }
}
