//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class planejamento_auto_avaliacao_impacto
    {
        public int INT_ID { get; set; }
        public int INT_ID_RESPONSAVEL { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public Nullable<System.DateTime> DATE_ULTIMA_EDICAO { get; set; }
        public Nullable<int> INT_ID_RESPONSAVEL_ULTIMA_ALTERACAO { get; set; }
        public string TXT_AUTO_AVALIACAO { get; set; }
        public string TXT_IMPACTO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public int INT_ID_PERIODO_PLANEJAMENTO { get; set; }
        public int INT_ID_ITEM { get; set; }
    
        public virtual funcionario funcionario { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        public virtual planejamento_item planejamento_item { get; set; }
        public virtual planejamento_periodo planejamento_periodo { get; set; }
    }
}
