//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class planejamento_periodo
    {
        public planejamento_periodo()
        {
            this.planejamento = new HashSet<planejamento>();
            this.planejamento_auto_avaliacao_impacto = new HashSet<planejamento_auto_avaliacao_impacto>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_CATEGORIA { get; set; }
        public System.DateTime DATE_INI { get; set; }
        public System.DateTime DATE_FIM { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual ICollection<planejamento> planejamento { get; set; }
        public virtual ICollection<planejamento_auto_avaliacao_impacto> planejamento_auto_avaliacao_impacto { get; set; }
        public virtual planejamento_categoria planejamento_categoria { get; set; }
    }
}
