//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class planejamento_responsavel
    {
        public int INT_ID { get; set; }
        public int INT_ID_RESPONSAVEL { get; set; }
        public Nullable<int> INT_ID_PLANEJAMENTO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public Nullable<int> INT_ID_PLANEJAMENTO_ITEM { get; set; }
    
        public virtual funcionario funcionario { get; set; }
        public virtual planejamento planejamento { get; set; }
        public virtual planejamento_item planejamento_item { get; set; }
    }
}
