//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ponto_critico
    {
        public ponto_critico()
        {
            this.documento_comprobatorio = new HashSet<documento_comprobatorio>();
            this.formulario_respostas = new HashSet<formulario_respostas>();
            this.potencial_risco = new HashSet<potencial_risco>();
            this.procedimento_critico_medida_precaucao = new HashSet<procedimento_critico_medida_precaucao>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_CERTIFICACAO { get; set; }
        public string TXT_DESCRICAO { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual certificacao certificacao { get; set; }
        public virtual ICollection<documento_comprobatorio> documento_comprobatorio { get; set; }
        public virtual ICollection<formulario_respostas> formulario_respostas { get; set; }
        public virtual ICollection<potencial_risco> potencial_risco { get; set; }
        public virtual ICollection<procedimento_critico_medida_precaucao> procedimento_critico_medida_precaucao { get; set; }
    }
}
