//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class portifolio_fornecedor
    {
        public int INT_ID { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public Nullable<int> INT_ID_LINHA_PRODUTO { get; set; }
        public Nullable<int> INT_ID_GRUPO_SERVICO { get; set; }
        public int INT_ID_CLIENTE { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual grupo_de_servico grupo_de_servico { get; set; }
        public virtual produto_linha produto_linha { get; set; }
    }
}
