//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class pre_financiamento
    {
        public pre_financiamento()
        {
            this.contrato = new HashSet<contrato>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_DESCRICAO { get; set; }
        public string TXT_CLAUSULA { get; set; }
        public string TXT_CLAUSULA_INGLES { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual ICollection<contrato> contrato { get; set; }
    }
}
