//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class premio_ft
    {
        public int INT_ID { get; set; }
        public Nullable<int> INT_ID_CONTRATO { get; set; }
        public decimal DECIMAL_VALOR_FT { get; set; }
        public bool BOOL_SALDO_INICIAL { get; set; }
        public System.DateTime DATE { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public Nullable<int> INT_ID_PAGAMENTO_RECEBIMENTO_FLUXO_DE_CAIXA { get; set; }
        public Nullable<bool> BOOL_CC_PG_FLUXO_CAIXA { get; set; }
        public Nullable<int> INT_ID_PAGAMENTO_PARCELA_EMPRESTIMO { get; set; }
        public Nullable<int> INT_ID_ORIGEM_DO_PRODUTO_NOTA_FISCAL { get; set; }
    
        public virtual contrato contrato { get; set; }
        public virtual origem_do_produto_nota_fiscal origem_do_produto_nota_fiscal { get; set; }
        public virtual pagamento_emprestimo pagamento_emprestimo { get; set; }
        public virtual pagamento_recebimento_fluxo_de_caixa pagamento_recebimento_fluxo_de_caixa { get; set; }
    }
}
