//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class procedimento_critico_medida_precaucao
    {
        public procedimento_critico_medida_precaucao()
        {
            this.formulario_respostas = new HashSet<formulario_respostas>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_PONTO_CRITICO { get; set; }
        public string TXT_DESCRICAO { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual ICollection<formulario_respostas> formulario_respostas { get; set; }
        public virtual ponto_critico ponto_critico { get; set; }
    }
}
