//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class produtos_contabeis
    {
        public produtos_contabeis()
        {
            this.configuracao_nota_filial = new HashSet<configuracao_nota_filial>();
            this.configuracao_plano_de_contas_nota = new HashSet<configuracao_plano_de_contas_nota>();
            this.cotacao_item = new HashSet<cotacao_item>();
            this.despesas_realizadas_contas_a_pg_e_rec = new HashSet<despesas_realizadas_contas_a_pg_e_rec>();
            this.estrutura_do_produto = new HashSet<estrutura_do_produto>();
            this.estrutura_do_produto1 = new HashSet<estrutura_do_produto>();
            this.lancamento_extras_codigos_contabeis = new HashSet<lancamento_extras_codigos_contabeis>();
            this.lote_produto = new HashSet<lote_produto>();
            this.movimentos_produtos_contabeis = new HashSet<movimentos_produtos_contabeis>();
            this.ordem_de_producao = new HashSet<ordem_de_producao>();
            this.ordem_de_producao_embalagens = new HashSet<ordem_de_producao_embalagens>();
            this.ordem_de_producao_produtos = new HashSet<ordem_de_producao_produtos>();
            this.ordem_de_producao_produtos_utilizados = new HashSet<ordem_de_producao_produtos_utilizados>();
            this.padrao_de_imposto_por_cfop = new HashSet<padrao_de_imposto_por_cfop>();
            this.pedido_faturamento_produto = new HashSet<pedido_faturamento_produto>();
            this.produtos_ccontabeis_referencia_terceiros = new HashSet<produtos_ccontabeis_referencia_terceiros>();
            this.produtos_contabeis1 = new HashSet<produtos_contabeis>();
            this.requisito_compra_itens = new HashSet<requisito_compra_itens>();
            this.tabela_codigo_produto_por_convenio = new HashSet<tabela_codigo_produto_por_convenio>();
            this.transferencia_produtos = new HashSet<transferencia_produtos>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_CODIGO_CONTABIL { get; set; }
        public string TXT_DESCRICAO_DO_PRODUTO { get; set; }
        public decimal FLOAT_SALDO_INICIAL { get; set; }
        public bool BOOL_REMESSA_RETORNO { get; set; }
        public decimal DECIMAL_VLR_UNITARIO { get; set; }
        public Nullable<int> INT_ID_COD_CONTABIL_COMPRA_VENDA { get; set; }
        public string CHAR_CATEGORIA_DO_PRODUTO { get; set; }
        public string TXT_CEST { get; set; }
        public string TXT_NCM { get; set; }
        public string TXT_GTIN { get; set; }
        public decimal DECIMAL_QTD_MAXIMA { get; set; }
        public decimal DECIMAL_QTD_MINIMA { get; set; }
        public bool BOOL_MATERIA_PRIMA { get; set; }
        public int INT_NUMERO_DE_CASAS_DECIMAIS { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public decimal DECIMAL_PESO_LIQUIDO { get; set; }
        public decimal DECIMAL_PESO_BRUTO { get; set; }
        public string TXT_CODIGO_DE_BARRAS { get; set; }
        public string TXT_UN { get; set; }
        public bool BOOL_PARAMETRIZAR { get; set; }
        public Nullable<int> INT_ID_LINHA_DO_PRODUTO { get; set; }
        public bool BOOL_PRODUTO_SERVICO { get; set; }
        public decimal DECIMAL_VLR_MINIMO { get; set; }
        public Nullable<int> INT_ID_UN_MEDIDA { get; set; }
    
        public virtual ICollection<configuracao_nota_filial> configuracao_nota_filial { get; set; }
        public virtual ICollection<configuracao_plano_de_contas_nota> configuracao_plano_de_contas_nota { get; set; }
        public virtual ICollection<cotacao_item> cotacao_item { get; set; }
        public virtual ICollection<despesas_realizadas_contas_a_pg_e_rec> despesas_realizadas_contas_a_pg_e_rec { get; set; }
        public virtual ICollection<estrutura_do_produto> estrutura_do_produto { get; set; }
        public virtual ICollection<estrutura_do_produto> estrutura_do_produto1 { get; set; }
        public virtual ICollection<lancamento_extras_codigos_contabeis> lancamento_extras_codigos_contabeis { get; set; }
        public virtual ICollection<lote_produto> lote_produto { get; set; }
        public virtual ICollection<movimentos_produtos_contabeis> movimentos_produtos_contabeis { get; set; }
        public virtual ICollection<ordem_de_producao> ordem_de_producao { get; set; }
        public virtual ICollection<ordem_de_producao_embalagens> ordem_de_producao_embalagens { get; set; }
        public virtual ICollection<ordem_de_producao_produtos> ordem_de_producao_produtos { get; set; }
        public virtual ICollection<ordem_de_producao_produtos_utilizados> ordem_de_producao_produtos_utilizados { get; set; }
        public virtual ICollection<padrao_de_imposto_por_cfop> padrao_de_imposto_por_cfop { get; set; }
        public virtual ICollection<pedido_faturamento_produto> pedido_faturamento_produto { get; set; }
        public virtual produto_linha produto_linha { get; set; }
        public virtual ICollection<produtos_ccontabeis_referencia_terceiros> produtos_ccontabeis_referencia_terceiros { get; set; }
        public virtual ICollection<produtos_contabeis> produtos_contabeis1 { get; set; }
        public virtual produtos_contabeis produtos_contabeis2 { get; set; }
        public virtual unidade_de_medida unidade_de_medida { get; set; }
        public virtual ICollection<requisito_compra_itens> requisito_compra_itens { get; set; }
        public virtual ICollection<tabela_codigo_produto_por_convenio> tabela_codigo_produto_por_convenio { get; set; }
        public virtual ICollection<transferencia_produtos> transferencia_produtos { get; set; }
    }
}
