//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class produtos_ccontabeis_referencia_terceiros
    {
        public int INT_ID { get; set; }
        public int INT_ID_PRODUTO { get; set; }
        public string TXT_CODIGO_REFERENCIA { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public int INT_ID_FORNECEDOR { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual produtos_contabeis produtos_contabeis { get; set; }
    }
}
