//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class projetos_realizados
    {
        public projetos_realizados()
        {
            this.projeto_cooperado = new HashSet<projeto_cooperado>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_PROJETO_DA_EMPRESA { get; set; }
        public decimal DECIMAL_VALOR { get; set; }
        public int INT_QUANTIDADE_PESSOAS_IMPACTADAS { get; set; }
        public Nullable<int> INT_ID_PLANEJAMENTO { get; set; }
        public Nullable<int> INT_ID_CLIENTE_FONTE_RESCURSO { get; set; }
        public string TXT_IMPACTO { get; set; }
        public string TXT_OBS { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public System.DateTime DATE_REALIZACAO { get; set; }
        public int INT_ID_CADASTRO { get; set; }
        public System.DateTime DATE_CADASTRO { get; set; }
        public Nullable<int> INT_ID_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DATE_ALTERACAO { get; set; }
        public Nullable<int> INT_ID_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DATE_EXCLUSAO { get; set; }
        public string TXT_CAMINHO_ARQUIVO { get; set; }
        public string TXT_CAMINHO_ARQUIVO_PDF { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        public virtual funcionario funcionario2 { get; set; }
        public virtual planejamento planejamento { get; set; }
        public virtual ICollection<projeto_cooperado> projeto_cooperado { get; set; }
        public virtual projetos_da_empresa projetos_da_empresa { get; set; }
    }
}
