//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class projeto_cooperado
    {
        public int INT_ID { get; set; }
        public int INT_ID_PROJETO_REALIZADO { get; set; }
        public int INT_ID_COOPERADO { get; set; }
        public bool BOOL_PRINCIPAL { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual cooperado cooperado { get; set; }
        public virtual projetos_realizados projetos_realizados { get; set; }
    }
}
