//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class recibo
    {
        public recibo()
        {
            this.movimento_bancario = new HashSet<movimento_bancario>();
            this.pagamento_emprestimo = new HashSet<pagamento_emprestimo>();
            this.recibo_cancelado = new HashSet<recibo_cancelado>();
            this.recibo_lotes = new HashSet<recibo_lotes>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_FUNC { get; set; }
        public System.DateTime DATE_RECIBO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public bool BOOL_PG { get; set; }
        public string TXT_OBS { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
    
        public virtual funcionario funcionario { get; set; }
        public virtual ICollection<movimento_bancario> movimento_bancario { get; set; }
        public virtual ICollection<pagamento_emprestimo> pagamento_emprestimo { get; set; }
        public virtual ICollection<recibo_cancelado> recibo_cancelado { get; set; }
        public virtual ICollection<recibo_lotes> recibo_lotes { get; set; }
    }
}
