//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class recibo_lotes
    {
        public int INT_ID { get; set; }
        public int INT_ID_RECIBO { get; set; }
        public Nullable<int> INT_ID_PEDIDO_COMPRA { get; set; }
        public Nullable<int> INT_ID_COMPLEMENTACAO { get; set; }
        public decimal DECIMAL_TOTAL_DESCONTOS { get; set; }
        public decimal DECIMAL_TOTAL_DA_NF { get; set; }
        public decimal DECIMAL_TOTAL_PG { get; set; }
        public bool BOOL_COMPL { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual complementacoes_lote complementacoes_lote { get; set; }
        public virtual lotes_do_fechamento_e_hedge lotes_do_fechamento_e_hedge { get; set; }
        public virtual recibo recibo { get; set; }
    }
}
