//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class referencia_hedge
    {
        public int INT_ID { get; set; }
        public int INT_ID_HEDGE { get; set; }
        public Nullable<int> INT_ID_LOTE_MERC_FUTURO { get; set; }
        public Nullable<int> INT_ID_CONTRATO { get; set; }
        public Nullable<int> INT_ID_ACC { get; set; }
        public Nullable<int> INT_ID_LOTE_FECHAMENTO_CAFE { get; set; }
        public decimal FLOAT_QUANTIDADE_FISICO { get; set; }
        public string TXT_FLAG_TIPO { get; set; }
        public bool BOOL_ACC { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual acc_com_hedge acc_com_hedge { get; set; }
        public virtual contrato contrato { get; set; }
        public virtual fechamento_mercado_futuro fechamento_mercado_futuro { get; set; }
        public virtual hedge hedge { get; set; }
        public virtual lotes_do_fechamento_e_hedge lotes_do_fechamento_e_hedge { get; set; }
    }
}
