//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class relacao_de_custos_da_formacao_de_preco
    {
        public int INT_ID { get; set; }
        public int INT_ID_FORMACAO_DE_PRECO { get; set; }
        public int INT_ID_CUSTO_DA_FORMACAO { get; set; }
        public float FLOAT_VALOR { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public bool BOOL_VALOR_FIXO_OU_PERCENTUAL { get; set; }
    
        public virtual custo_da_formacao_de_preco custo_da_formacao_de_preco { get; set; }
        public virtual formacao_de_preco formacao_de_preco { get; set; }
    }
}
