//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class relacao_notas_descontoacrescimo_lotes_fechamento
    {
        public int INT_ID { get; set; }
        public int INT_ID_RELACAO_DE_NOTAS_DESCONTO_ACRESCIMO { get; set; }
        public Nullable<int> INT_ID_LOTES_FECHAMENTO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public Nullable<int> INT_ID_COMPLEMENTACOES_LOTE { get; set; }
    
        public virtual complementacoes_lote complementacoes_lote { get; set; }
        public virtual lotes_do_fechamento_e_hedge lotes_do_fechamento_e_hedge { get; set; }
        public virtual relacao_de_notas_desc_acrescimo relacao_de_notas_desc_acrescimo { get; set; }
    }
}
