//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class relacao_situacao_norma
    {
        public int INT_ID { get; set; }
        public int INT_ID_SITUACAO_NORMA { get; set; }
        public Nullable<int> INT_ID_AUTORIZACAO_GENERICA { get; set; }
        public Nullable<int> INT_ID_INSTRUCAO_PREPARO { get; set; }
        public Nullable<int> INT_ID_CONTRATO { get; set; }
        public Nullable<int> INT_ID_COMPOSICAO { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual autorizacao_generica autorizacao_generica { get; set; }
        public virtual composicao_amostra composicao_amostra { get; set; }
        public virtual contrato contrato { get; set; }
        public virtual instrucao_preparo instrucao_preparo { get; set; }
        public virtual situacao_norma situacao_norma { get; set; }
    }
}
