//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class remocao_de_lotes
    {
        public int INT_ID { get; set; }
        public int INT_ID_RESPONSAVEL { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public System.DateTime DATE_REMOCAO { get; set; }
        public int INT_ID_ALA_ORIGEM { get; set; }
        public int INT_ID_ALA_DESTINO { get; set; }
        public int INT_ID_ALA_DO_LOTE { get; set; }
        public decimal DECIMAL_KG_BAIXA { get; set; }
        public Nullable<System.DateTime> DATE_PEGAR_LOTE { get; set; }
    
        public virtual alas_do_armazem alas_do_armazem { get; set; }
        public virtual alas_do_armazem alas_do_armazem1 { get; set; }
        public virtual alas_do_armazem_lotes alas_do_armazem_lotes { get; set; }
        public virtual funcionario funcionario { get; set; }
    }
}
