//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class requisito_compra_itens
    {
        public requisito_compra_itens()
        {
            this.cotacao_item = new HashSet<cotacao_item>();
        }
    
        public int INT_ID { get; set; }
        public Nullable<int> INT_ID_PRODUTO { get; set; }
        public string TXT_PRODUTO { get; set; }
        public bool BOOL_PRODUTO_SERVICO { get; set; }
        public decimal DECIMAL_QTD { get; set; }
        public string TXT_PROJETO_ITEM_PLANEJAMENTO { get; set; }
        public System.DateTime DATE_PRAZO { get; set; }
        public string TXT_OBS { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public int INT_ID_REQUISITO { get; set; }
        public Nullable<System.DateTime> DATE_INI_COTACAO { get; set; }
        public Nullable<System.DateTime> DATE_COMPRA { get; set; }
        public Nullable<System.DateTime> DATE_FINALIZOU { get; set; }
        public string TXT_STATUS { get; set; }
        public int INT_ID_UN_MEDIDA { get; set; }
    
        public virtual ICollection<cotacao_item> cotacao_item { get; set; }
        public virtual produtos_contabeis produtos_contabeis { get; set; }
        public virtual requisicao_compra requisicao_compra { get; set; }
        public virtual unidade_de_medida unidade_de_medida { get; set; }
    }
}
