//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class requisicao_compra
    {
        public requisicao_compra()
        {
            this.requisito_compra_itens = new HashSet<requisito_compra_itens>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_NR_REQUISITO { get; set; }
        public int INT_ID_SETOR { get; set; }
        public int INT_ID_SOLICITANTE { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public Nullable<int> INT_ID_ALTEROU { get; set; }
        public Nullable<System.DateTime> DATE_ALTEROU { get; set; }
        public Nullable<int> INT_ID_EXCLUIU { get; set; }
        public Nullable<System.DateTime> DATE_EXCLUIU { get; set; }
        public string TXT_STATUS { get; set; }
        public Nullable<System.DateTime> DATE_INICIO_COTACAP { get; set; }
        public Nullable<System.DateTime> DATE_COMPRA { get; set; }
        public Nullable<System.DateTime> DATE_FINALIZOU { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual funcionario funcionario { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        public virtual funcionario funcionario2 { get; set; }
        public virtual setor setor { get; set; }
        public virtual ICollection<requisito_compra_itens> requisito_compra_itens { get; set; }
    }
}
