//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class revisoes_pop
    {
        public revisoes_pop()
        {
            this.autorizacao_generica = new HashSet<autorizacao_generica>();
            this.lote_produto = new HashSet<lote_produto>();
            this.ordem_de_producao = new HashSet<ordem_de_producao>();
            this.ordem_de_producao_resultado = new HashSet<ordem_de_producao_resultado>();
            this.ordem_de_producao_tempo = new HashSet<ordem_de_producao_tempo>();
            this.origem_do_produto = new HashSet<origem_do_produto>();
            this.solicitacao_de_retirada = new HashSet<solicitacao_de_retirada>();
            this.transferencia_entre_almoxarifado = new HashSet<transferencia_entre_almoxarifado>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_REVISAO { get; set; }
        public string TXT_FLAG_TIPO_DOC { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
    
        public virtual ICollection<autorizacao_generica> autorizacao_generica { get; set; }
        public virtual ICollection<lote_produto> lote_produto { get; set; }
        public virtual ICollection<ordem_de_producao> ordem_de_producao { get; set; }
        public virtual ICollection<ordem_de_producao_resultado> ordem_de_producao_resultado { get; set; }
        public virtual ICollection<ordem_de_producao_tempo> ordem_de_producao_tempo { get; set; }
        public virtual ICollection<origem_do_produto> origem_do_produto { get; set; }
        public virtual ICollection<solicitacao_de_retirada> solicitacao_de_retirada { get; set; }
        public virtual ICollection<transferencia_entre_almoxarifado> transferencia_entre_almoxarifado { get; set; }
    }
}
