//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfid_chip
    {
        public rfid_chip()
        {
            this.alas_do_armazem = new HashSet<alas_do_armazem>();
            this.alas_do_armazem_chip_rfid = new HashSet<alas_do_armazem_chip_rfid>();
            this.alas_do_armazem_lotes = new HashSet<alas_do_armazem_lotes>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_IDENTIFICACAO { get; set; }
        public string CHAR_LOCAL { get; set; }
        public System.DateTime DATE_INICIOU { get; set; }
        public Nullable<System.DateTime> DATE_FINALIZOU { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public int INT_ID_EMPRESA { get; set; }
    
        public virtual ICollection<alas_do_armazem> alas_do_armazem { get; set; }
        public virtual ICollection<alas_do_armazem_chip_rfid> alas_do_armazem_chip_rfid { get; set; }
        public virtual ICollection<alas_do_armazem_lotes> alas_do_armazem_lotes { get; set; }
        public virtual empresa empresa { get; set; }
    }
}
