//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitacao_de_amostra_lote
    {
        public int INT_ID { get; set; }
        public int INT_ID_SOLICITACAO_DE_AMOSTRA { get; set; }
        public Nullable<int> INT_ID_CADASTRO_ENTRADA { get; set; }
        public Nullable<int> INT_ID_LOTE_ARMAZEM_TERCEIRO { get; set; }
        public Nullable<int> INT_ID_LOTE_RESULTADO_REBENEFICIO { get; set; }
        public decimal DECIMAL_SACAS { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public Nullable<int> INT_NF { get; set; }
        public Nullable<decimal> DECIMAL_VLR_UNITARIO { get; set; }
        public bool BOOL_SEPARADO { get; set; }
        public int INT_ID_LANCOU_LOTE { get; set; }
        public Nullable<int> INT_ID_SEPAROU_AMOSTRA { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public Nullable<System.DateTime> DATE_SEPAROU { get; set; }
        public decimal DECIMAL_KG { get; set; }
        public string TXT_MOTIVO { get; set; }
    
        public virtual cadastro_entrada cadastro_entrada { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        public virtual lote_armazem_terceiros lote_armazem_terceiros { get; set; }
        public virtual lote_resultado_rebeneficio lote_resultado_rebeneficio { get; set; }
        public virtual solicitacao_de_amostra solicitacao_de_amostra { get; set; }
    }
}
