//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabela_ibpt
    {
        public decimal NACIONAL { get; set; }
        public decimal IMPORTADO { get; set; }
        public decimal ESTADUAL { get; set; }
        public decimal MUNICIPAL { get; set; }
        public System.DateTime VIGENCIA_INI { get; set; }
        public System.DateTime VIGENCIA_FINAL { get; set; }
        public string TXT_CHAVE { get; set; }
        public string TXT_VERSAO { get; set; }
        public string TXT_FONTE { get; set; }
        public string TXT_NCM { get; set; }
    }
}
