//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabela_codigo_produto_por_convenio
    {
        public int INT_ID { get; set; }
        public int INT_ID_CONVENIO_PLANO_MEDICO { get; set; }
        public int INT_ID_PRODUTO { get; set; }
        public string TXT_CODIGO { get; set; }
        public decimal DECIMAL_VLR { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public string CHAR_CATEGORIA { get; set; }
    
        public virtual convenio_plano_de_saude convenio_plano_de_saude { get; set; }
        public virtual produtos_contabeis produtos_contabeis { get; set; }
    }
}
