//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class talhao_variedade
    {
        public int INT_ID { get; set; }
        public int INT_ID_TALHAO { get; set; }
        public Nullable<int> INT_ID_VARIEDADE { get; set; }
        public System.DateTime DATE_PLANTIO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public System.DateTime DATE_CADASTRO { get; set; }
        public int INT_ID_CADASTRO { get; set; }
        public Nullable<System.DateTime> DATE_ALTERACAO { get; set; }
        public Nullable<int> INT_ID_ALTEROU { get; set; }
        public Nullable<System.DateTime> DATE_EXCLUSAO { get; set; }
        public Nullable<int> INT_ID_EXCLUSAO { get; set; }
        public decimal DECIMAL_NUM_PES { get; set; }
        public int ID_GRUPO_VARIEDADE { get; set; }
    
        public virtual funcionario funcionario { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        public virtual funcionario funcionario2 { get; set; }
        public virtual grupo_variedade grupo_variedade { get; set; }
        public virtual talhao talhao { get; set; }
        public virtual variedades variedades { get; set; }
    }
}
