//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class talhao_unificar
    {
        public int INT_ID { get; set; }
        public int INT_ID_SOLICITACAO_UNIFICACAO { get; set; }
        public int INT_ID_TALHAO { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual solicitacao_de_unificacao_divisao_de_talhoes solicitacao_de_unificacao_divisao_de_talhoes { get; set; }
        public virtual talhao talhao { get; set; }
    }
}
