//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class telefone
    {
        public int INT_ID { get; set; }
        public int INT_ID_COOPERADO { get; set; }
        public string TXT_TELEFONE { get; set; }
        public string TXT_OBS { get; set; }
        public bool BOOL_FLAG_ATIVO_EXCLUIDO { get; set; }
    
        public virtual cooperado cooperado { get; set; }
    }
}
