//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_de_criterio
    {
        public tipo_de_criterio()
        {
            this.formulario_sub_item = new HashSet<formulario_sub_item>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_DESCRICAO { get; set; }
        public bool BOOL_ELIMINATORIO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public decimal DECIMAL_PESO { get; set; }
    
        public virtual ICollection<formulario_sub_item> formulario_sub_item { get; set; }
    }
}
