//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_de_permissao_alas_do_armazem
    {
        public tipo_de_permissao_alas_do_armazem()
        {
            this.alas_do_armazem = new HashSet<alas_do_armazem>();
            this.tipo_de_permissao_alas_do_armazem_normas = new HashSet<tipo_de_permissao_alas_do_armazem_normas>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_DESCRICAO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public int INT_ID_EMPRESA { get; set; }
        public string TXT_COR { get; set; }
    
        public virtual ICollection<alas_do_armazem> alas_do_armazem { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual ICollection<tipo_de_permissao_alas_do_armazem_normas> tipo_de_permissao_alas_do_armazem_normas { get; set; }
    }
}
