//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_cafe_rebeneficiado
    {
        public tipo_cafe_rebeneficiado()
        {
            this.contrato = new HashSet<contrato>();
            this.fechamento_mercado_futuro = new HashSet<fechamento_mercado_futuro>();
            this.instrucao_lote_resultado_para_gerar = new HashSet<instrucao_lote_resultado_para_gerar>();
            this.lote_resultado_rebeneficio = new HashSet<lote_resultado_rebeneficio>();
            this.tipo_lote_rebeneficio_para_gerar = new HashSet<tipo_lote_rebeneficio_para_gerar>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_TIPO { get; set; }
        public int INT_ID_EMPRESA { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual ICollection<contrato> contrato { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual ICollection<fechamento_mercado_futuro> fechamento_mercado_futuro { get; set; }
        public virtual ICollection<instrucao_lote_resultado_para_gerar> instrucao_lote_resultado_para_gerar { get; set; }
        public virtual ICollection<lote_resultado_rebeneficio> lote_resultado_rebeneficio { get; set; }
        public virtual ICollection<tipo_lote_rebeneficio_para_gerar> tipo_lote_rebeneficio_para_gerar { get; set; }
    }
}
