//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_amostra
    {
        public tipo_amostra()
        {
            this.amostra_solo_foliar = new HashSet<amostra_solo_foliar>();
        }
    
        public int INT_ID { get; set; }
        public string TXT_DESCRICAO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public bool BOOL_SOLO_FOLIAR { get; set; }
    
        public virtual ICollection<amostra_solo_foliar> amostra_solo_foliar { get; set; }
    }
}
