//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class transferencia_recurso_planejamento_utilizado
    {
        public transferencia_recurso_planejamento_utilizado()
        {
            this.recurso_utilizado_outra_fonte = new HashSet<recurso_utilizado_outra_fonte>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_TRANSFERENCIA_RECURSO { get; set; }
        public int INT_ID_PLANEJAMENTO { get; set; }
        public decimal DECIMAL_TAXA_DOLAR { get; set; }
        public decimal DECIMAL_TOTAL_DOLAR { get; set; }
        public decimal DECIMAL_TOTAL_REAIS { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual planejamento planejamento { get; set; }
        public virtual ICollection<recurso_utilizado_outra_fonte> recurso_utilizado_outra_fonte { get; set; }
        public virtual transferencia_recursos transferencia_recursos { get; set; }
    }
}
