//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class transferencia_recursos
    {
        public transferencia_recursos()
        {
            this.transferencia_recurso_planejamento_utilizado = new HashSet<transferencia_recurso_planejamento_utilizado>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_NOVO_PLANEJAMENTO { get; set; }
        public decimal DECIMAL_TAXA_DOLAR_MEDIA { get; set; }
        public decimal DECIMAL_TOTAL_DOLAR { get; set; }
        public decimal DECIMAL_TOTAL_REAIS { get; set; }
        public System.DateTime DATE_TRANSFERENCIA { get; set; }
        public string TXT_OBS { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public bool BOOL_SALDO_INICIAL { get; set; }
    
        public virtual planejamento planejamento { get; set; }
        public virtual ICollection<transferencia_recurso_planejamento_utilizado> transferencia_recurso_planejamento_utilizado { get; set; }
    }
}
