//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class transferencia_entre_almoxarifado
    {
        public transferencia_entre_almoxarifado()
        {
            this.transferencia_produtos = new HashSet<transferencia_produtos>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_ALMOXARIFADO_ORIGEM { get; set; }
        public int INT_ID_ALMOXARIFADO_DESTINO { get; set; }
        public System.DateTime DATE_TRANSFERENCIA { get; set; }
        public int INT_ID_RESPONSAVEL { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public int INT_ID_EMPRESA { get; set; }
        public Nullable<int> INT_ID_ULTIMA_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DATE_ULTIMA_ALTERACAO { get; set; }
        public string TXT_OBS { get; set; }
        public Nullable<int> INT_ID_EXCLUIU { get; set; }
        public Nullable<System.DateTime> DATE_EXCLUIU { get; set; }
        public string TXT_NR_TRANSFERENCIA { get; set; }
        public bool BOOL_MOVIMENTAR_ALMOXARIFADO_DESTINO { get; set; }
        public Nullable<int> INT_ID_REVISAO_POP { get; set; }
    
        public virtual almoxarifado almoxarifado { get; set; }
        public virtual almoxarifado almoxarifado1 { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        public virtual funcionario funcionario2 { get; set; }
        public virtual revisoes_pop revisoes_pop { get; set; }
        public virtual ICollection<transferencia_produtos> transferencia_produtos { get; set; }
    }
}
