//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class valor_diario_de_cada_carteira
    {
        public int INT_ID { get; set; }
        public decimal FLOAT_VALOR_FISICO { get; set; }
        public decimal FLOAT_VALOR_FUTURO { get; set; }
        public int INT_ID_GRUPO_DA_CARTEIRA { get; set; }
        public System.DateTime DATE_DATA_DA_POSICAO { get; set; }
        public decimal FLOAT_DOLAR_CONVERSAO_BOLSA { get; set; }
        public System.DateTime DATE_VENCIMENTO { get; set; }
    
        public virtual grupo_da_carteira grupo_da_carteira { get; set; }
    }
}
