//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class variedades
    {
        public variedades()
        {
            this.talhao_variedade = new HashSet<talhao_variedade>();
        }
    
        public int INT_ID { get; set; }
        public int ID_GRUPO { get; set; }
        public string TXT_DESCRICAO { get; set; }
        public bool BOOL_ATIVO { get; set; }
    
        public virtual grupo_variedade grupo_variedade { get; set; }
        public virtual ICollection<talhao_variedade> talhao_variedade { get; set; }
    }
}
