//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class venda_prestacao_servico
    {
        public venda_prestacao_servico()
        {
            this.baixa_valor_adiantado = new HashSet<baixa_valor_adiantado>();
            this.movimentos_produtos_contabeis = new HashSet<movimentos_produtos_contabeis>();
            this.nota_fiscal = new HashSet<nota_fiscal>();
        }
    
        public int INT_ID { get; set; }
        public Nullable<int> INT_ID_CLIENTE { get; set; }
        public Nullable<int> INT_ID_COOPERADO { get; set; }
        public bool BOOL_COOPERADO { get; set; }
        public string TXT_OBS { get; set; }
        public bool BOOL_PRESTACAO { get; set; }
        public decimal DECIMAL_VINCULADO_ADIANTAMENTO { get; set; }
        public bool BOOL_DOACAO { get; set; }
        public Nullable<int> INT_ID_FORMA_PARCELAMENTO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public int INT_ID_FUNCIONARIO { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public System.DateTime DATE_VENDA { get; set; }
        public int INT_ID_EMPRESA { get; set; }
        public bool BOOL_ECOMMERCE { get; set; }
        public bool BOOL_CONSUMIDOR_FINAL { get; set; }
        public Nullable<int> INT_ID_TALHAO { get; set; }
        public Nullable<System.DateTime> DATE_SAIDA { get; set; }
        public bool BOOL_PERMUTA { get; set; }
        public Nullable<int> INT_ID_PEDIDO { get; set; }
    
        public virtual ICollection<baixa_valor_adiantado> baixa_valor_adiantado { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual cooperado cooperado { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual ICollection<movimentos_produtos_contabeis> movimentos_produtos_contabeis { get; set; }
        public virtual ICollection<nota_fiscal> nota_fiscal { get; set; }
        public virtual pedido_faturamento pedido_faturamento { get; set; }
        public virtual talhao talhao { get; set; }
    }
}
