//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace objRecebendoAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class agendamento_certificacao_api
    {
        public agendamento_certificacao_api()
        {
            this.agendamento_formulario_ser_aplicado = new HashSet<agendamento_formulario_ser_aplicado_api>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_COLABORADOR_QUE_VAI_APLICAR { get; set; }
        public int INT_ID_TIPO_INSPECAO { get; set; }
        public System.DateTime DATE_AGENDAMENTO { get; set; }
        public Nullable<int> INT_ID_COOPERADO { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public System.TimeSpan TEMPO_ESTIMADO { get; set; }
        public int INT_ID_CADASTRO { get; set; }
        public System.DateTime DATE_CADASTRO { get; set; }
        public Nullable<int> INT_ID_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DATE_ALTERACAO { get; set; }
        public Nullable<int> INT_ID_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DATE_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DATE_INICIO { get; set; }
        public Nullable<System.DateTime> DATE_FINALIZACAO { get; set; }
        public bool BOOL_SINCRONIZACAO_INICIO { get; set; }
        public Nullable<System.DateTime> DATE_SINCRONIZACAO { get; set; }
        public bool BOOL_SINCRONIZACAO_FINALIZOU { get; set; }
        public Nullable<System.DateTime> DATE_SINC_FIN { get; set; }
        public Nullable<int> INT_ID_SOLICITACAO_VISITA { get; set; }
        public bool BOOL_FAZER_EXERCICIO_RASTREABILIDADE { get; set; }
        public bool BOOL_ITENS_ESPECIFICOS_FORMULARIO_COMPLETO { get; set; }
        public Nullable<int> INT_ID_SETOR { get; set; }
        public Nullable<int> INT_ID_RESPONSAVEL_SETOR { get; set; }
        public bool BOOL_VISITA_CANCELADA { get; set; }
        public string TXT_MOTIVO { get; set; }
        public bool BOOL_REMARCADA { get; set; }
        public string TXT_OBS { get; set; }
        public bool BOOL_INTERNO { get; set; }
         
        public virtual solicitar_visita_api solicitar_visita { get; set; }

        public virtual ICollection<agendamento_formulario_ser_aplicado_api> agendamento_formulario_ser_aplicado { get; set; }
    }
}
