//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace objRecebendoAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class formulario_resposta_documento_comprobatorio_api
    {
        public int INT_ID { get; set; }
        public int INT_ID_DOCUMENTO_COMPROBATORIO { get; set; }
        public int INT_ID_FORMULARIO_RESPOSTA { get; set; }
        public string TXT_OBS { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public int INT_ID_LANCAMENTO { get; set; }
        public System.DateTime DATE_LANCAMENTO { get; set; }
        public Nullable<int> INT_ID_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DATE_ALTERACAO { get; set; }
        public Nullable<int> INT_ID_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DATE_EXCLUSAO { get; set; }
    
        public virtual formulario_respostas_api formulario_respostas { get; set; }
    }
}
