//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace objRecebendoAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class formulario_respostas_api
    {
        public formulario_respostas_api()
        {
            this.form_resposta_nc_criterio = new HashSet<form_resposta_nc_criterio_api>();
            this.formulario_resposta_documento_comprobatorio = new HashSet<formulario_resposta_documento_comprobatorio_api>();
            this.formulario_resposta_evidencia= new HashSet<formulario_resposta_evidencia_api>();
            this.formulario_resposta_seletiva= new HashSet<formulario_resposta_seletiva_api>();
            this.solicitar_visita = new HashSet<solicitar_visita_api>();
        }
    
        public int INT_ID { get; set; }
        public int INT_ID_FORMULARIO_APP { get; set; }
        public Nullable<int> INT_ID_FORM_SUB_ITEM { get; set; }
        public Nullable<bool> BOOL_C_NC_NA_ { get; set; }
        public Nullable<decimal> DECIMAL_NOTA { get; set; }
        public string TXT_CONSTATACAO_INSPETOR { get; set; }
        public string TXT_RESPOSTA_PMO { get; set; }
        public string TXT_OBS { get; set; }
        public Nullable<decimal> DECIMAL_NOTA_TOTAL { get; set; }
        public string TXT_LATITUDE { get; set; }
        public string TXT_LONGITUDE { get; set; }
        public int INT_ID_CADASTRO { get; set; }
        public System.DateTime DATE_CADASTRO { get; set; }
        public Nullable<int> INT_ID_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DATE_ALTERACAO { get; set; }
        public Nullable<int> INT_ID_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DATE_EXCLUSAO { get; set; }
        public string TXT_ACAO_CORRETIVA { get; set; }
        public Nullable<System.DateTime> DATE_PRAZO_ENTRAR_EM_CONTATO_ANALISTA_SCI { get; set; }
        public Nullable<bool> BOOL_RESOLVIDO { get; set; }
        public Nullable<System.DateTime> DATA_PRAZO_RESOLVER_NC { get; set; }
        public Nullable<System.DateTime> DATE_RESOLVIDO { get; set; }
        public bool BOOL_REINCIDENTE { get; set; }
        public Nullable<bool> BOOL_MANTIDA_PELO_ANALISTA_SCI { get; set; }
        public string TXT_OBS_ANALISTA_SCI { get; set; }
        public Nullable<bool> BOOL_MANTIDA_PELO_GESTOR_SCI { get; set; }
        public string TXT_OBS_MANTIDA_PELO_GESTOR_SCI { get; set; }
        public bool BOOL_ATIVO { get; set; }
        public string TXT_OBS_RESOLUCAO { get; set; }
        public bool BOOL_MEDIDA_PRECAUCAO { get; set; }
        public Nullable<int> INT_ID_PONTO_CRITICO { get; set; }
        public Nullable<int> INT_ID_POTENCIAL_RISCO { get; set; }
        public Nullable<int> INT_ID_PROCEDIMENTO_CRITICO { get; set; }
        public string TXT_OBS_PONTO_CRITICO { get; set; }
        public string TXT_OBS_PROCEDIMENTO_CRITICO { get; set; }
        public string TXT_OBS_POTENCIAL_RISCO { get; set; }
        public Nullable<int> INT_ID_FORMULARIO_SUBITEM_RANK { get; set; }
    
        public virtual ICollection<form_resposta_nc_criterio_api> form_resposta_nc_criterio { get; set; }
        public virtual formulario_aplicar_api formulario_aplicar { get; set; }
        public virtual ICollection<formulario_resposta_documento_comprobatorio_api> formulario_resposta_documento_comprobatorio { get; set; }
        public virtual ICollection<formulario_resposta_evidencia_api> formulario_resposta_evidencia { get; set; }
        public virtual ICollection<formulario_resposta_seletiva_api> formulario_resposta_seletiva { get; set; }
        public virtual ICollection<solicitar_visita_api> solicitar_visita{ get; set; }
    }
}
